import ServiceLocator from 'ljit-lib/service-locator';
import DEFAULTSvg from './lotteries/default.svg';
import AHQ3Svg from './lotteries/AHQ3.svg';
import BJ5F3DSvg from './lotteries/BJ5F3D.svg';
import BJ5FCSvg from './lotteries/BJ5FC.svg';
import BJKL8Svg from './lotteries/BJKL8.svg';
import BJPC28Svg from './lotteries/BJPC28.svg';
import BJPK10Svg from './lotteries/BJPK10.svg';
import BJQ3Svg from './lotteries/BJQ3.svg';
import CCKL10FSvg from './lotteries/CCKL10F.svg';
import CCSSSSvg from './lotteries/CCSSS.svg';
import CND35FCSvg from './lotteries/CND35FC.svg';
import CNDPC28Svg from './lotteries/CNDPC28.svg';
import CS11S5Svg from './lotteries/CS11S5.svg';
import CSU11S5Svg from './lotteries/CSU11S5.svg';
import DJ15FCSvg from './lotteries/DJ15FC.svg';
import FC3DSvg from './lotteries/FC3D.svg';
import HB11S5Svg from './lotteries/HB11S5.svg';
import HK6HCSvg from './lotteries/HK6HC.svg';
import HLC11S5Svg from './lotteries/HLC11S5.svg';
import HNKL10FSvg from './lotteries/HNKL10F.svg';
import HNSSCSvg from './lotteries/HNSSC.svg';
import JLQ3Svg from './lotteries/JLQ3.svg';
import KD11S5Svg from './lotteries/KD11S5.svg';
import KDKL10FSvg from './lotteries/KDKL10F.svg';
import KSQ3Svg from './lotteries/KSQ3.svg';
import LN11S5Svg from './lotteries/LN11S5.svg';
import MD2FCSvg from './lotteries/MD2FC.svg';
import NMKQ3Svg from './lotteries/NMKQ3.svg';
import PL35Svg from './lotteries/PL35.svg';
import QQFFCSvg from './lotteries/QQFFC.svg';
import SD11S5Svg from './lotteries/SD11S5.svg';
import SH11S5Svg from './lotteries/SH11S5.svg';
import SHQ3Svg from './lotteries/SHQ3.svg';
import TCKL10FSvg from './lotteries/TCKL10F.svg';
import TCSSCSvg from './lotteries/TCSSC.svg';
import TS5FCSvg from './lotteries/TS5FC.svg';
import TS10FCSvg from './lotteries/TS10FC.svg';
import TSFFCSvg from './lotteries/TSFFC.svg';
import TW5F3DSvg from './lotteries/TW5F3D.svg';
import TW5FCSvg from './lotteries/TW5FC.svg';
import TWKL8Svg from './lotteries/TWKL8.svg';
import TWPC28Svg from './lotteries/TWPC28.svg';
import TWPK10Svg from './lotteries/TWPK10.svg';
import XC11S5Svg from './lotteries/XC11S5.svg';
import XCSSCSvg from './lotteries/XCSSC.svg';
import XYFTSvg from './lotteries/XYFT.svg';
import YKKL10FSvg from './lotteries/YKKL10F.svg';
import YNSSCSvg from './lotteries/YNSSC.svg';

import logo from './logo/logo.svg';

const locator = new ServiceLocator();

locator.register('DEFAULT', DEFAULTSvg);
locator.register('AHQ3', AHQ3Svg);
locator.register('BJ5F3D', BJ5F3DSvg);
locator.register('BJ5FC', BJ5FCSvg);
locator.register('BJKL8', BJKL8Svg);
locator.register('BJPC28', BJPC28Svg);
locator.register('BJPK10', BJPK10Svg);
locator.register('BJQ3', BJQ3Svg);
locator.register('CCKL10F', CCKL10FSvg);
locator.register('CCSSS', CCSSSSvg);
locator.register('CND35FC', CND35FCSvg);
locator.register('CNDPC28', CNDPC28Svg);
locator.register('CS11S5', CS11S5Svg);
locator.register('CSU11S5', CSU11S5Svg);
locator.register('DJ15FC', DJ15FCSvg);
locator.register('FC3D', FC3DSvg);
locator.register('HB11S5', HB11S5Svg);
locator.register('HK6HC', HK6HCSvg);
locator.register('HLC11S5', HLC11S5Svg);
locator.register('HNKL10F', HNKL10FSvg);
locator.register('HNSSC', HNSSCSvg);
locator.register('JLQ3', JLQ3Svg);
locator.register('KD11S5', KD11S5Svg);
locator.register('KDKL10F', KDKL10FSvg);
locator.register('KSQ3', KSQ3Svg);
locator.register('LN11S5', LN11S5Svg);
locator.register('MD2FC', MD2FCSvg);
locator.register('NMKQ3', NMKQ3Svg);
locator.register('PL35', PL35Svg);
locator.register('QQFFC', QQFFCSvg);
locator.register('SD11S5', SD11S5Svg);
locator.register('SH11S5', SH11S5Svg);
locator.register('SHQ3', SHQ3Svg);
locator.register('TCKL10F', TCKL10FSvg);
locator.register('TCSSC', TCSSCSvg);
locator.register('TS5FC', TS5FCSvg);
locator.register('TS10FC', TS10FCSvg);
locator.register('TSFFC', TSFFCSvg);
locator.register('TW5F3D', TW5F3DSvg);
locator.register('TW5FC', TW5FCSvg);
locator.register('TWKL8', TWKL8Svg);
locator.register('TWPC28', TWPC28Svg);
locator.register('TWPK10', TWPK10Svg);
locator.register('XC11S5', XC11S5Svg);
locator.register('XCSSC', XCSSCSvg);
locator.register('XYFT', XYFTSvg);
locator.register('YKKL10F', YKKL10FSvg);
locator.register('YNSSC', YNSSCSvg);

locator.register('logo', logo);

export default locator;
