import * as Fields from './fields';

export const FieldNameEnum = {
	BANK_NAME: 'bankName',
	BANK_ACCOUNT: 'bankAccount',
	DEPOSIT_BANK: 'depositBank',
	REMIND_ACCOUNT: 'remindAccount',
	RECHARGE_NAME: 'rechargeName',
	RECHARGE_TYPE: 'rechargeType',
	TRADE_NAME: 'tradeName',
	DEACTIVATION_AMOUNT: 'deactivationAmount',
	PAYEE: 'payee',
	RECEIVED_AMOUNT: 'receivedAmount',
	SEND_AMOUNT: 'SendAmount',
	SINGLE_PAYMENT_LIMIT: 'singlePaymentLimit',
	LEVEL: 'level',
	STATUS: 'status',
	SHOPPING_REDIRECTION: 'shoppingRedirection',
	HIDDEN_DEVICE: 'hiddenDevice',
	PAYMENT_PLATFORM: 'paymentPlatform',
};
const {
	BANK_NAME,
	BANK_ACCOUNT,
	DEPOSIT_BANK,
	REMIND_ACCOUNT,
	RECHARGE_NAME,
	RECHARGE_TYPE,
	TRADE_NAME,
	DEACTIVATION_AMOUNT,
	PAYEE,
	RECEIVED_AMOUNT,
	SEND_AMOUNT,
	SINGLE_PAYMENT_LIMIT,
	LEVEL,
	STATUS,
	SHOPPING_REDIRECTION,
	HIDDEN_DEVICE,
	PAYMENT_PLATFORM,
} = FieldNameEnum;

export const FormTypeEnum = {
	BANK: 'bank',
	SHOPPING: 'shopping',
	PAYMENT_TRANSFER: 'payment-transfer',
};

export const FieldNameGroupMap = {
	[FormTypeEnum.BANK]: [
		BANK_NAME,
		BANK_ACCOUNT,
		RECHARGE_TYPE,
		DEPOSIT_BANK,
		RECEIVED_AMOUNT,
		REMIND_ACCOUNT,
		LEVEL,
		PAYEE,
		STATUS,
	],
	[FormTypeEnum.SHOPPING]: [
		RECHARGE_NAME,
		LEVEL,
		RECHARGE_TYPE,
		TRADE_NAME,
		RECEIVED_AMOUNT,
		DEACTIVATION_AMOUNT,
		STATUS,
		SHOPPING_REDIRECTION,
		HIDDEN_DEVICE,
	],
	[FormTypeEnum.PAYMENT_TRANSFER]: [
		RECHARGE_NAME,
		LEVEL,
		PAYMENT_PLATFORM,
		TRADE_NAME,
		SEND_AMOUNT,
		SINGLE_PAYMENT_LIMIT,
		STATUS,
		SHOPPING_REDIRECTION,
	],
};

export const FieldsMap = {
	[BANK_NAME]: Fields.BankName,
	[BANK_ACCOUNT]: Fields.BankAccount,
	[DEPOSIT_BANK]: Fields.DepositBank,
	[REMIND_ACCOUNT]: Fields.RemindAccount,
	[RECHARGE_NAME]: Fields.RechargeName,
	[RECHARGE_TYPE]: Fields.RechargeType,
	[TRADE_NAME]: Fields.TradeName,
	[DEACTIVATION_AMOUNT]: Fields.DeactivationAmount,
	[PAYEE]: Fields.Payee,
	[RECEIVED_AMOUNT]: Fields.ReceivedAmount,
	[SEND_AMOUNT]: Fields.SendAmount,
	[SINGLE_PAYMENT_LIMIT]: Fields.SinglePaymentLimit,
	[LEVEL]: Fields.Level,
	[STATUS]: Fields.Status,
	[SHOPPING_REDIRECTION]: Fields.ShoppingRedirection,
	[HIDDEN_DEVICE]: Fields.HiddenDevice,
	[PAYMENT_PLATFORM]: Fields.PaymentPlatform,
};
