export default [
	{
		_id: 1,
		name: 'Lexy Gergher',
		age: 32,
		address0: '2 Vidon Parkway',
		address1: '500 Northridge Circle',
		address2: '85 Jana Road',
		address3: '9169 Cambridge Avenue',
		address4: '2 Prairie Rose Place',
	},
	{
		_id: 2,
		name: 'Illa Temple',
		age: 42,
		address0: '56 Maywood Park',
		address1: '4592 Magdeline Point',
		address2: '680 Daystar Center',
		address3: '433 Florence Crossing',
		address4: '36 Trailsway Point',
	},
	{
		_id: 3,
		name: 'Kaitlin Poacher',
		age: 42,
		address0: '09 Monica Junction',
		address1: '21050 Independence Road',
		address2: '244 Lien Plaza',
		address3: '1 Del Mar Court',
		address4: '937 Waywood Junction',
	},
	{
		_id: 4,
		name: 'Theresa Rushsorth',
		age: 32,
		address0: '40 Schurz Street',
		address1: '010 Randy Junction',
		address2: '4 Nevada Alley',
		address3: '5137 Schlimgen Way',
		address4: '02414 Meadow Ridge Circle',
	},
	{
		_id: 5,
		name: 'Issie Djordjevic',
		age: 34,
		address0: '629 Doe Crossing Park',
		address1: '3 Scoville Place',
		address2: '9 Pennsylvania Court',
		address3: '304 Sage Point',
		address4: '1 Pepper Wood Way',
	},
];
