// Notify handling
import { notifyHandlingActions, } from '../../../lib/notify-handler';
export const { CATCH_NOTIFY_HANDLING, } = notifyHandlingActions;

// Application
export const START_INITIALIZE_APPLICATION = 'START_INITIALIZE_APPLICATION';
export const INITIALIZE_APPLICATION_SUCCESS = 'INITIALIZE_APPLICATION_SUCCESS';
export const INITIALIZE_APPLICATION_FAILED = 'INITIALIZE_APPLICATION_FAILED';
// Me
export const START_FETCH_ME = 'START_FETCH_ME';
export const FETCH_ME_FAILED = 'FETCH_ME_FAILED';
export const FETCH_ME_SUCCESS = 'FETCH_ME_SUCCESS';

// Users
export const START_FETCH_USERS = 'START_FETCH_USERS';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILED = 'FETCH_USERS_FAILED';

// User Detail
export const START_FETCH_USER_DETAIL = 'START_FETCH_USER_DETAIL';
export const FETCH_USER_DETAIL_SUCCESS = 'FETCH_USER_DETAIL_SUCCESS';
export const FETCH_USER_DETAIL_FAILED = 'FETCH_USER_DETAIL_FAILED';
export const START_UPDATE_USER_DETAIL_BLOCK_BETTING = 'START_UPDATE_USER_DETAIL_BLOCK_BETTING';
export const UPDATE_USER_DETAIL_BLOCK_BETTING_SUCCESS = 'UPDATE_USER_DETAIL_BLOCK_BETTING_SUCCESS';
export const UPDATE_USER_DETAIL_BLOCK_BETTING_FAILED = 'UPDATE_USER_DETAIL_BLOCK_BETTING_FAILED';
export const START_UPDATE_USER_DETAIL_BLOCK_DEPOSIT = 'START_UPDATE_USER_DETAIL_BLOCK_DEPOSIT';
export const UPDATE_USER_DETAIL_BLOCK_DEPOSIT_SUCCESS = 'UPDATE_USER_DETAIL_BLOCK_DEPOSIT_SUCCESS';
export const UPDATE_USER_DETAIL_BLOCK_DEPOSIT_FAILED = 'UPDATE_USER_DETAIL_BLOCK_DEPOSIT_FAILED';
export const START_UPDATE_USER_DETAIL_BLOCK_WITHDRAWAL = 'START_UPDATE_USER_DETAIL_BLOCK_WITHDRAWAL';
export const UPDATE_USER_DETAIL_BLOCK_WITHDRAWAL_SUCCESS = 'UPDATE_USER_DETAIL_BLOCK_WITHDRAWAL_SUCCESS';
export const UPDATE_USER_DETAIL_BLOCK_WITHDRAWAL_FAILED = 'UPDATE_USER_DETAIL_BLOCK_WITHDRAWAL_FAILED';
export const START_UPDATE_USER_DETAIL_FUNDS_PASSWORD = 'START_UPDATE_USER_DETAIL_FUNDS_PASSWORD';
export const UPDATE_USER_DETAIL_FUNDS_PASSWORD_SUCCESS = 'UPDATE_USER_DETAIL_FUNDS_PASSWORD_SUCCESS';
export const UPDATE_USER_DETAIL_FUNDS_PASSWORD_FAILED = 'UPDATE_USER_DETAIL_FUNDS_PASSWORD_FAILED';
export const START_UPDATE_USER_DETAIL_FIN_PASSWORD = 'START_UPDATE_USER_DETAIL_FIN_PASSWORD';
export const UPDATE_USER_DETAIL_FIN_PASSWORD_SUCCESS = 'UPDATE_USER_DETAIL_FIN_PASSWORD_SUCCESS';
export const UPDATE_USER_DETAIL_FIN_PASSWORD_FAILED = 'UPDATE_USER_DETAIL_FIN_PASSWORD_FAILED';
export const START_UPDATE_USER_DETAIL_LOGIN_PASSWORD = 'START_UPDATE_USER_DETAIL_LOGIN_PASSWORD';
export const UPDATE_USER_DETAIL_LOGIN_PASSWORD_SUCCESS = 'UPDATE_USER_DETAIL_LOGIN_PASSWORD_SUCCESS';
export const UPDATE_USER_DETAIL_LOGIN_PASSWORD_FAILED = 'UPDATE_USER_DETAIL_LOGIN_PASSWORD_FAILED';
export const START_UPDATE_USER_DETAIL_STATUS = 'START_UPDATE_USER_DETAIL_STATUS';
export const UPDATE_USER_DETAIL_STATUS_SUCCESS = 'UPDATE_USER_DETAIL_STATUS_SUCCESS';
export const UPDATE_USER_DETAIL_STATUS_FAILED = 'UPDATE_USER_DETAIL_STATUS_FAILED';
export const START_UPDATE_USER_DETAIL_NICKNAME = 'START_UPDATE_USER_DETAIL_NICKNAME';
export const UPDATE_USER_DETAIL_NICKNAME_SUCCESS = 'UPDATE_USER_DETAIL_NICKNAME_SUCCESS';
export const UPDATE_USER_DETAIL_NICKNAME_FAILED = 'UPDATE_USER_DETAIL_NICKNAME_FAILED';
export const START_UPDATE_USER_DETAIL_TYPE = 'START_UPDATE_USER_DETAIL_TYPE';
export const UPDATE_USER_DETAIL_TYPE_SUCCESS = 'UPDATE_USER_DETAIL_TYPE_SUCCESS';
export const UPDATE_USER_DETAIL_TYPE_FAILED = 'UPDATE_USER_DETAIL_TYPE_FAILED';
export const START_UPDATE_USER_DETAIL_BLOCK_DEPOSIT_TRANSFER = 'START_UPDATE_USER_DETAIL_BLOCK_DEPOSIT_TRANSFER';
export const UPDATE_USER_DETAIL_BLOCK_DEPOSIT_TRANSFER_SUCCESS = 'UPDATE_USER_DETAIL_BLOCK_DEPOSIT_TRANSFER_SUCCESS';
export const UPDATE_USER_DETAIL_BLOCK_DEPOSIT_TRANSFER_FAILED = 'UPDATE_USER_DETAIL_BLOCK_DEPOSIT_TRANSFER_FAILED';
export const START_UPDATE_USER_DETAIL_BLOCK_DIVIDEND_TRANSFER = 'START_UPDATE_USER_DETAIL_BLOCK_DIVIDEND_TRANSFER';
export const UPDATE_USER_DETAIL_BLOCK_DIVIDEND_TRANSFER_SUCCESS = 'UPDATE_USER_DETAIL_BLOCK_DIVIDEND_TRANSFER_SUCCESS';
export const UPDATE_USER_DETAIL_BLOCK_DIVIDEND_TRANSFER_FAILED = 'UPDATE_USER_DETAIL_BLOCK_DIVIDEND_TRANSFER_FAILED';
export const START_UPDATE_USER_DETAIL_ALERT_USER = 'START_UPDATE_USER_DETAIL_ALERT_USER';
export const UPDATE_USER_DETAIL_ALERT_USER_SUCCESS = 'UPDATE_USER_DETAIL_ALERT_USER_SUCCESS';
export const UPDATE_USER_DETAIL_ALERT_USER_FAILED = 'UPDATE_USER_DETAIL_ALERT_USER_FAILED';
export const START_UPDATE_USER_DETAIL_LEVEL = 'START_UPDATE_USER_DETAIL_LEVEL';
export const UPDATE_USER_DETAIL_LEVEL_SUCCESS = 'UPDATE_USER_DETAIL_LEVEL_SUCCESS';
export const UPDATE_USER_DETAIL_LEVEL_FAILED = 'UPDATE_USER_DETAIL_LEVEL_FAILED';
export const START_UPDATE_USER_DETAIL_PAYER = 'START_UPDATE_USER_DETAIL_PAYER';
export const UPDATE_USER_DETAIL_PAYER_SUCCESS = 'UPDATE_USER_DETAIL_PAYER_SUCCESS';
export const UPDATE_USER_DETAIL_PAYER_FAILED = 'UPDATE_USER_DETAIL_PAYER_FAILED';

// User Comment
export const START_FETCH_USER_COMMENTS = 'START_FETCH_USER_COMMENTS';
export const FETCH_USER_COMMENTS_SUCCESS = 'FETCH_USER_COMMENTS_SUCCESS';
export const FETCH_USER_COMMENTS_FAILED = 'FETCH_USER_COMMENTS_FAILED';
export const START_ADD_USER_COMMENT = 'START_ADD_USER_COMMENT';
export const ADD_USER_COMMENT_SUCCESS = 'ADD_USER_COMMENT_SUCCESS';
export const ADD_USER_COMMENT_FAILED = 'ADD_USER_COMMENT_FAILED';
export const START_CANCEL_PINNED_USER_COMMENT = 'START_CANCEL_PINNED_USER_COMMENT';
export const CANCEL_PINNED_USER_COMMENT_SUCCESS = 'CANCEL_PINNED_USER_COMMENT_SUCCESS';
export const CANCEL_PINNED_USER_COMMENT_FAILED = 'CANCEL_PINNED_USER_COMMENT_FAILED';

// User profile
export const START_FETCH_USER_PROFILE = 'START_FETCH_USER_PROFILE';
export const FETCH_USER_PROFILE_SUCCESS = 'FETCH_USER_PROFILE_SUCCESS';
export const FETCH_USER_PROFILE_FAILED = 'FETCH_USER_PROFILE_FAILED';
export const START_UPDATE_USER_NICKNAME = 'START_UPDATE_USER_NICKNAME';
export const UPDATE_USER_NICKNAME_SUCCESS = 'UPDATE_USER_NICKNAME_SUCCESS';
export const UPDATE_USER_NICKNAME_FAILED = 'UPDATE_USER_NICKNAME_FAILED';
export const START_UPDATE_USER_PAYER = 'START_UPDATE_USER_PAYER';
export const UPDATE_USER_PAYER_SUCCESS = 'UPDATE_USER_PAYER_SUCCESS';
export const UPDATE_USER_PAYER_FAILED = 'UPDATE_USER_PAYER_FAILED';
export const START_UPDATE_USER_ZHUANDIAN = 'START_UPDATE_USER_ZHUANDIAN';
export const UPDATE_USER_ZHUANDIAN_SUCCESS = 'UPDATE_USER_ZHUANDIAN_SUCCESS';
export const UPDATE_USER_ZHUANDIAN_FAILED = 'UPDATE_USER_ZHUANDIAN_FAILED';
export const START_UPDATE_USER_TYPE = 'START_UPDATE_USER_TYPE';
export const UPDATE_USER_TYPE_SUCCESS = 'UPDATE_USER_TYPE_SUCCESS';
export const UPDATE_USER_TYPE_FAILED = 'UPDATE_USER_TYPE_FAILED';
export const START_UPDATE_USER_GREETING = 'START_UPDATE_USER_GREETING';
export const UPDATE_USER_GREETING_SUCCESS = 'UPDATE_USER_GREETING_SUCCESS';
export const UPDATE_USER_GREETING_FAILED = 'UPDATE_USER_GREETING_FAILED';
export const START_ENABLE_USER_WITHDRAWABLE = 'START_ENABLE_USER_WITHDRAWABLE';
export const ENABLE_USER_WITHDRAWABLE_SUCCESS = 'ENABLE_USER_WITHDRAWABLE_SUCCESS';
export const ENABLE_USER_WITHDRAWABLE_FAILED = 'ENABLE_USER_WITHDRAWABLE_FAILED';
export const START_DISABLE_USER_WITHDRAWABLE = 'START_DISABLE_USER_WITHDRAWABLE';
export const DISABLE_USER_WITHDRAWABLE_SUCCESS = 'DISABLE_USER_WITHDRAWABLE_SUCCESS';
export const DISABLE_USER_WITHDRAWABLE_FAILED = 'DISABLE_USER_WITHDRAWABLE_FAILED';
export const START_ENABLE_USER_DEPOSIT = 'START_ENABLE_USER_DEPOSIT';
export const ENABLE_USER_DEPOSIT_SUCCESS = 'ENABLE_USER_DEPOSIT_SUCCESS';
export const ENABLE_USER_DEPOSIT_FAILED = 'ENABLE_USER_DEPOSIT_FAILED';
export const START_DISABLE_USER_DEPOSIT = 'START_DISABLE_USER_DEPOSIT';
export const DISABLE_USER_DEPOSIT_SUCCESS = 'DISABLE_USER_DEPOSIT_SUCCESS';
export const DISABLE_USER_DEPOSIT_FAILED = 'DISABLE_USER_DEPOSIT_FAILED';
export const START_FETCH_USER_ACCOUNT = 'START_FETCH_USER_ACCOUNT';
export const FETCH_USER_ACCOUNT_SUCCESS = 'FETCH_USER_ACCOUNT_SUCCESS';
export const FETCH_USER_ACCOUNT_FAILED = 'FETCH_USER_ACCOUNT_FAILED';
export const START_UPDATE_USER_LOGIN_PASSWORD = 'START_UPDATE_USER_LOGIN_PASSWORD';
export const UPDATE_USER_LOGIN_PASSWORD_SUCCESS = 'UPDATE_USER_LOGIN_PASSWORD_SUCCESS';
export const UPDATE_USER_LOGIN_PASSWORD_FAILED = 'UPDATE_USER_LOGIN_PASSWORD_FAILED';
export const START_UPDATE_USER_BETTING_PASSWORD = 'START_UPDATE_USER_BETTING_PASSWORD';
export const UPDATE_USER_BETTING_PASSWORD_SUCCESS = 'UPDATE_USER_BETTING_PASSWORD_SUCCESS';
export const UPDATE_USER_BETTING_PASSWORD_FAILED = 'UPDATE_USER_BETTING_PASSWORD_FAILED';
export const START_UPDATE_USER_FUNDS_PASSWORD = 'START_UPDATE_USER_FUNDS_PASSWORD';
export const UPDATE_USER_FUNDS_PASSWORD_SUCCESS = 'UPDATE_USER_FUNDS_PASSWORD_SUCCESS';
export const UPDATE_USER_FUNDS_PASSWORD_FAILED = 'UPDATE_USER_FUNDS_PASSWORD_FAILED';
export const START_DELETE_USER_SECURITY_QUESTIONS = 'START_DELETE_USER_SECURITY_QUESTIONS';
export const DELETE_USER_SECURITY_QUESTIONS_SUCCESS = 'DELETE_USER_SECURITY_QUESTIONS_SUCCESS';
export const DELETE_USER_SECURITY_QUESTIONS_FAILED = 'DELETE_USER_SECURITY_QUESTIONS_FAILED';
export const START_ENABLE_USER_FUNDS = 'START_ENABLE_USER_FUNDS';
export const ENABLE_USER_FUNDS_SUCCESS = 'ENABLE_USER_FUNDS_SUCCESS';
export const ENABLE_USER_FUNDS_FAILED = 'ENABLE_USER_FUNDS_FAILED';
export const START_DISABLE_USER_FUNDS = 'START_DISABLE_USER_FUNDS';
export const DISABLE_USER_FUNDS_SUCCESS = 'DISABLE_USER_FUNDS_SUCCESS';
export const DISABLE_USER_FUNDS_FAILED = 'DISABLE_USER_FUNDS_FAILED';
export const START_ENABLE_USER_LOGIN_GEO_VALIDATION = 'START_ENABLE_USER_LOGIN_GEO_VALIDATION';
export const ENABLE_USER_LOGIN_GEO_VALIDATION_SUCCESS = 'ENABLE_USER_LOGIN_GEO_VALIDATION_SUCCESS';
export const ENABLE_USER_LOGIN_GEO_VALIDATION_FAILED = 'ENABLE_USER_LOGIN_GEO_VALIDATION_FAILED';
export const START_DISABLE_USER_LOGIN_GEO_VALIDATION = 'START_DISABLE_USER_LOGIN_GEO_VALIDATION';
export const DISABLE_USER_LOGIN_GEO_VALIDATION_SUCCESS = 'DISABLE_USER_LOGIN_GEO_VALIDATION_SUCCESS';
export const DISABLE_USER_LOGIN_GEO_VALIDATION_FAILED = 'DISABLE_USER_LOGIN_GEO_VALIDATION_FAILED';
export const START_DISABLE_USER_GOOGLE_TOTP = 'START_DISABLE_USER_GOOGLE_TOTP';
export const DISABLE_USER_GOOGLE_TOTP_SUCCESS = 'DISABLE_USER_GOOGLE_TOTP_SUCCESS';
export const DISABLE_USER_GOOGLE_TOTP_FAILED = 'DISABLE_USER_GOOGLE_TOTP_FAILED';
export const START_ENABLE_USER_BETTING = 'START_ENABLE_USER_BETTING';
export const ENABLE_USER_BETTING_SUCCESS = 'ENABLE_USER_BETTING_SUCCESS';
export const ENABLE_USER_BETTING_FAILED = 'ENABLE_USER_BETTING_FAILED';
export const START_DISABLE_USER_BETTING = 'START_DISABLE_USER_BETTING';
export const DISABLE_USER_BETTING_SUCCESS = 'DISABLE_USER_BETTING_SUCCESS';
export const DISABLE_USER_BETTING_FAILED = 'DISABLE_USER_BETTING_FAILED';

export const START_UPDATE_USER_BONUS = 'START_UPDATE_USER_BONUS';
export const UPDATE_USER_BONUS_SUCCESS = 'UPDATE_USER_BONUS_SUCCESS';
export const UPDATE_USER_BONUS_FAILED = 'UPDATE_USER_BONUS_FAILED';

export const START_UPDATE_USER_FIXED_WAGE = 'START_UPDATE_USER_FIXED_WAGE';
export const UPDATE_USER_FIXED_WAGE_SUCCESS = 'UPDATE_USER_FIXED_WAGE_SUCCESS';
export const UPDATE_USER_FIXED_WAGE_FAILED = 'UPDATE_USER_FIXED_WAGE_FAILED';

export const START_FETCH_USER_WALLETS = 'START_FETCH_USER_WALLETS';
export const FETCH_USER_WALLETS_SUCCESS = 'FETCH_USER_WALLETS_SUCCESS';
export const FETCH_USER_WALLETS_FAILED = 'FETCH_USER_WALLETS_FAILED';

export const START_ENABLE_USER = 'START_ENABLE_USER';
export const ENABLE_USER_FAILED = 'ENABLE_USER_FAILED';
export const ENABLE_USER_SUCCESS = 'ENABLE_USER_SUCCESS';
export const START_DISABLE_USER = 'START_DISABLE_USER';
export const DISABLE_USER_FAILED = 'DISABLE_USER_FAILED';
export const DISABLE_USER_SUCCESS = 'DISABLE_USER_SUCCESS';
export const START_ENABLE_USER_DIVIDEND = 'START_ENABLE_USER_DIVIDEND';
export const ENABLE_USER_DIVIDEND_SUCCESS = 'ENABLE_USER_DIVIDEND_SUCCESS';
export const ENABLE_USER_DIVIDEND_FAILED = 'ENABLE_USER_DIVIDEND_FAILED';
export const START_DISABLE_USER_DIVIDEND = 'START_DISABLE_USER_DIVIDEND';
export const DISABLE_USER_DIVIDEND_SUCCESS = 'DISABLE_USER_DIVIDEND_SUCCESS';
export const DISABLE_USER_DIVIDEND_FAILED = 'DISABLE_USER_DIVIDEND_FAILED';
export const START_DISABLE_USER_TRANSFER = 'START_DISABLE_USER_TRANSFER';
export const DISABLE_USER_TRANSFER_SUCCESS = 'DISABLE_USER_TRANSFER_SUCCESS';
export const DISABLE_USER_TRANSFER_FAILED = 'DISABLE_USER_TRANSFER_FAILED';
export const START_ENABLE_USER_TRANSFER = 'START_ENABLE_USER_TRANSFER';
export const ENABLE_USER_TRANSFER_SUCCESS = 'ENABLE_USER_TRANSFER_SUCCESS';
export const ENABLE_USER_TRANSFER_FAILED = 'ENABLE_USER_TRANSFER_FAILED';

export const START_FETCH_USER_DIVIDEND_SETTINGS = 'START_FETCH_USER_DIVIDEND_SETTINGS';
export const FETCH_USER_DIVIDEND_SETTINGS_SUCCESS = 'FETCH_USER_DIVIDEND_SETTINGS_SUCCESS';
export const FETCH_USER_DIVIDEND_SETTINGS_FAILED = 'FETCH_USER_DIVIDEND_SETTINGS_FAILED';
export const START_UPDTATE_USER_DIVIDEND_SETTINGS = 'START_UPDTATE_USER_DIVIDEND_SETTINGS';
export const UPDTATE_USER_DIVIDEND_SETTINGS_SUCCESS = 'UPDTATE_USER_DIVIDEND_SETTINGS_SUCCESS';
export const UPDTATE_USER_DIVIDEND_SETTINGS_FAILED = 'UPDTATE_USER_DIVIDEND_SETTINGS_FAILED';

export const START_FETCH_USER = 'START_FETCH_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED';

export const START_INIT_USER_DETAILS_PAGE = 'START_INIT_USER_DETAILS_PAGE';
export const INIT_USER_DETAILS_PAGE_SUCCESS = 'INIT_USER_DETAILS_PAGE_SUCCESS';
export const INIT_USER_DETAILS_PAGE_FAILED = 'INIT_USER_DETAILS_PAGE_FAILED';
export const SET_HAS_INIT_USER_DETAIL_PAGE = 'SET_HAS_INIT_USER_DETAIL_PAGE';

export const START_INIT_USER_DIVIDEND_WAGE_RULE_PAGE = 'START_INIT_USER_DIVIDEND_WAGE_RULE_PAGE';
export const INIT_USER_DIVIDEND_WAGE_RULE_PAGE_SUCCESS = 'INIT_USER_DIVIDEND_WAGE_RULE_PAGE_SUCCESS';
export const INIT_USER_DIVIDEND_WAGE_RULE_PAGE_FAILED = 'INIT_USER_DIVIDEND_WAGE_RULE_PAGE_FAILED';

export const START_FETCH_USER_STATS = 'START_FETCH_USER_STATS';
export const FETCH_USER_STATS_SUCCESS = 'FETCH_USER_STATS_SUCCESS';
export const FETCH_USER_STATS_FAILED = 'FETCH_USER_STATS_FAILED';

// User Finance Level
export const START_FETCH_USER_FINANCE_LEVEL = 'START_FETCH_USER_FINANCE_LEVEL';
export const FETCH_USER_FINANCE_LEVEL_SUCCESS = 'FETCH_USER_FINANCE_LEVEL_SUCCESS';
export const FETCH_USER_FINANCE_LEVEL_FAILED = 'FETCH_USER_FINANCE_LEVEL_FAILED';
export const START_UPDATE_USER_FINANCE_LEVEL = 'START_UPDATE_USER_FINANCE_LEVEL';
export const UPDATE_USER_FINANCE_LEVEL_SUCCESS = 'UPDATE_USER_FINANCE_LEVEL_SUCCESS';
export const UPDATE_USER_FINANCE_LEVEL_FAILED = 'UPDATE_USER_FINANCE_LEVEL_FAILED';

// User Bank Card
export const START_FETCH_USER_BANK_CARDS = 'START_FETCH_USER_BANK_CARDS';
export const FETCH_USER_BANK_CARDS_SUCCESS = 'FETCH_USER_BANK_CARDS_SUCCESS';
export const FETCH_USER_BANK_CARDS_FAILED = 'FETCH_USER_BANK_CARDS_FAILED';
export const START_CREATE_USER_BANK_CARD = 'START_CREATE_USER_BANK_CARD';
export const CREATE_USER_BANK_CARD_SUCCESS = 'CREATE_USER_BANK_CARD_SUCCESS';
export const CREATE_USER_BANK_CARD_FAILED = 'CREATE_USER_BANK_CARD_FAILED';
export const START_DELETE_USER_BANK_CARD = 'START_DELETE_USER_BANK_CARD';
export const DELETE_USER_BANK_CARD_SUCCESS = 'DELETE_USER_BANK_CARD_SUCCESS';
export const DELETE_USER_BANK_CARD_FAILED = 'DELETE_USER_BANK_CARD_FAILED';
export const START_ENABLE_USER_BANK_CARD_WITHDRAWABLE = 'START_ENABLE_USER_BANK_CARD_WITHDRAWABLE';
export const ENABLE_USER_BANK_CARD_WITHDRAWABLE_SUCCESS = 'ENABLE_USER_BANK_CARD_WITHDRAWABLE_SUCCESS';
export const ENABLE_USER_BANK_CARD_WITHDRAWABLE_FAILED = 'ENABLE_USER_BANK_CARD_WITHDRAWABLE_FAILED';
export const START_UPDATE_USER_BANK_CARD_NUMBER = 'START_UPDATE_USER_BANK_CARD_NUMBER';
export const UPDATE_USER_BANK_CARD_UNMBER_SUCCESS = 'UPDATE_USER_BANK_CARD_UNMBER_SUCCESS';
export const UPDATE_USER_BANK_CARD_UNMBER_FAILED = 'UPDATE_USER_BANK_CARD_UNMBER_FAILED';
export const START_ENABLE_USER_BANK_CARD = 'START_ENABLE_USER_BANK_CARD';
export const ENABLE_USER_BANK_CARD_SUCCESS = 'ENABLE_USER_BANK_CARD_SUCCESS';
export const ENABLE_USER_BANK_CARD_FAILED = 'ENABLE_USER_BANK_CARD_FAILED';
export const START_DISABLE_USER_BANK_CARD = 'START_DISABLE_USER_BANK_CARD';
export const DISABLE_USER_BANK_CARD_SUCCESS = 'DISABLE_USER_BANK_CARD_SUCCESS';
export const DISABLE_USER_BANK_CARD_FAILED = 'DISABLE_USER_BANK_CARD_FAILED';

export const START_FETCH_LOTTERY_CLASSES_AND_LOTTERIES = 'START_FETCH_LOTTERY_CLASSES_AND_LOTTERIES';
export const FETCH_LOTTERY_CLASSES_AND_LOTTERIES_SUCCESS = 'FETCH_LOTTERY_CLASSES_AND_LOTTERIES_SUCCESS';
export const FETCH_LOTTERY_CLASSES_AND_LOTTERIES_FAILED = 'FETCH_LOTTERY_CLASSES_AND_LOTTERIES_FAILED';
export const START_UPDATE_LOTTERY_STATUS = 'START_UPDATE_LOTTERY_STATUS';
export const UPDATE_LOTTERY_STATUS_SUCCESS = 'UPDATE_LOTTERY_STATUS_SUCCESS';
export const UPDATE_LOTTERY_STATUS_FAILED = 'UPDATE_LOTTERY_STATUS_FAILED';
export const START_UPDATE_LOTTERIES_ORDERING_AND_HOTTAG = 'START_UPDATE_LOTTERIES_ORDERING_AND_HOTTAG';
export const UPDATE_LOTTERIES_ORDERING_AND_HOTTAG_SUCCESS = 'UPDATE_LOTTERIES_ORDERING_AND_HOTTAG_SUCCESS';
export const UPDATE_LOTTERIES_ORDERING_AND_HOTTAG_FAILED = 'UPDATE_LOTTERIES_ORDERING_AND_HOTTAG_FAILED';
export const START_UPDATE_LOTTERY_CLASS_STATUS = 'START_UPDATE_LOTTERY_CLASS_STATUS';
export const UPDATE_LOTTERY_CLASS_STATUS_SUCCESS = 'UPDATE_LOTTERY_CLASS_STATUS_SUCCESS';
export const UPDATE_LOTTERY_CLASS_STATUS_FAILED = 'UPDATE_LOTTERY_CLASS_STATUS_FAILED';

export const START_FETCH_LOTTERY_PLAYS = 'START_FETCH_LOTTERY_PLAYS';
export const FETCH_LOTTERY_PLAYS_SUCCESS = 'FETCH_LOTTERY_PLAYS_SUCCESS';
export const FETCH_LOTTERY_PLAYS_FAILED = 'FETCH_LOTTERY_PLAYS_FAILED';
export const START_UPDATE_LOTTERY_PLAYS_STATUS = 'START_UPDATE_LOTTERY_PLAYS_STATUS';
export const UPDATE_LOTTERY_PLAYS_STATUS_SUCCESS = 'UPDATE_LOTTERY_PLAYS_STATUS_SUCCESS';
export const UPDATE_LOTTERY_PLAYS_STATUS_FAILED = 'UPDATE_LOTTERY_PLAYS_STATUS_FAILED';
export const START_UPDATE_LOTTERY_PLAYS_BONUS = 'START_UPDATE_LOTTERY_PLAYS_BONUS';
export const UPDATE_LOTTERY_PLAYS_BONUS_SUCCESS = 'UPDATE_LOTTERY_PLAYS_BONUS_SUCCESS';
export const UPDATE_LOTTERY_PLAYS_BONUS_FAILED = 'UPDATE_LOTTERY_PLAYS_BONUS_FAILED';

export const START_FETCH_LOTTERY_PLAY_CONDITIONS = 'START_FETCH_LOTTERY_PLAY_CONDITIONS';
export const FETCH_LOTTERY_PLAY_CONDITIONS_SUCCESS = 'FETCH_LOTTERY_PLAY_CONDITIONS_SUCCESS';
export const FETCH_LOTTERY_PLAY_CONDITIONS_FAILED = 'FETCH_LOTTERY_PLAY_CONDITIONS_FAILED';

export const START_FETCH_BETTING_RECORDS = 'START_FETCH_BETTING_RECORDS';
export const FETCH_BETTING_RECORDS_SUCCESS = 'FETCH_BETTING_RECORDS_SUCCESS';
export const FETCH_BETTING_RECORDS_FAILED = 'FETCH_BETTING_RECORDS_FAILED';

export const START_FETCH_TRACE_RECORDS = 'START_FETCH_TRACE_RECORDS';
export const FETCH_TRACE_RECORDS_SUCCESS = 'FETCH_TRACE_RECORDS_SUCCESS';
export const FETCH_TRACE_RECORDS_FAILED = 'FETCH_TRACE_RECORDS_FAILED';

export const START_FETCH_TRACE_RECORD_BETTINGS = 'START_FETCH_TRACE_RECORD_BETTINGS';
export const FETCH_TRACE_RECORD_BETTINGS_SUCCESS = 'FETCH_TRACE_RECORD_BETTINGS_SUCCESS';
export const FETCH_TRACE_RECORD_BETTINGS_FAILED = 'FETCH_TRACE_RECORD_BETTINGS_FAILED';

export const START_FETCH_PLATFORM = 'START_FETCH_PLATFORM';
export const FETCH_PLATFORM_SUCCESS = 'FETCH_PLATFORM_SUCCESS';
export const FETCH_PLATFORM_FAILED = 'FETCH_PLATFORM_FAILED';

export const START_UPDATE_PLATFORM_FIXED_WAGE = 'START_UPDATE_PLATFORM_FIXED_WAGE';
export const UPDATE_PLATFORM_FIXED_WAGE_SUCCESS = 'UPDATE_PLATFORM_FIXED_WAGE_SUCCESS';
export const UPDATE_PLATFORM_FIXED_WAGE_FAILED = 'UPDATE_PLATFORM_FIXED_WAGE_FAILED';

// TODO change update name from API when API complete
export const START_UPDATE_BONUS_RULES = 'START_UPDATE_BONUS_RULES';
export const UPDATE_BONUS_RULES_SUCCESS = 'UPDATE_BONUS_RULES_SUCCESS';
export const UPDATE_BONUS_RULES_FAILED = 'UPDATE_BONUS_RULES_FAILED';

export const START_UPDATE_PLATFORM_DIVIDEND_SETTINGS = 'START_UPDATE_PLATFORM_DIVIDEND_SETTINGS';
export const UPDATE_PLATFORM_DIVIDEND_SETTINGS_SUCCESS = 'UPDATE_PLATFORM_DIVIDEND_SETTINGS_SUCCESS';
export const UPDATE_PLATFORM_DIVIDEND_SETTINGS_FAILED = 'UPDATE_PLATFORM_DIVIDEND_SETTINGS_FAILED';

export const START_FETCH_ADMIN_USERS = 'START_FETCH_ADMIN_USERS';
export const START_CREATE_ADMIN_USER = 'START_CREATE_ADMIN_USER';
export const START_UPDATE_ADMIN_USER = 'START_UPDATE_ADMIN_USER';
export const FETCH_ADMIN_USERS_FAILED = 'FETCH_ADMIN_USERS_FAILED';
export const FETCH_ADMIN_USERS_SUCCESS = 'FETCH_ADMIN_USERS_SUCCESS';
export const CREATE_ADMIN_USER_SUCCESS = 'CREATE_ADMIN_USER_SUCCESS';
export const CREATE_ADMIN_USER_FAILED = 'CREATE_ADMIN_USER_FAILED';
export const UPDATE_ADMIN_USER_SUCCESS = 'UPDATE_ADMIN_USER_SUCCESS';
export const UPDATE_ADMIN_USER_FAILED = 'UPDATE_ADMIN_USER_FAILED';
export const START_FETCH_STAFF_ROLES = 'START_FETCH_STAFF_ROLES';
export const FETCH_STAFF_ROLES_SUCCESS = 'FETCH_STAFF_ROLES_SUCCESS';
export const FETCH_STAFF_ROLES_FAILED = 'FETCH_STAFF_ROLES_FAILED';
export const START_UPDATE_STAFF_PASSWORD = 'START_UPDATE_STAFF_PASSWORD';
export const UPDATE_STAFF_PASSWORD_SUCCESS = 'UPDATE_STAFF_PASSWORD_SUCCESS';
export const UPDATE_STAFF_PASSWORD_FAILED = 'UPDATE_STAFF_PASSWORD_FAILED';

// 投注記錄
export const START_FETCH_BET_RECORDS = 'START_FETCH_BET_RECORDS';
export const FETCH_BET_RECORDS_SUCCESS = 'FETCH_BET_RECORDS_SUCCESS';
export const FETCH_BET_RECORDS_FAILED = 'FETCH_BET_RECORDS_FAILED';

export const START_INIT_LOTTERY_PLAY_MANAGEMENT_PAGE = 'START_INIT_LOTTERY_PLAY_MANAGEMENT_PAGE';
export const INIT_LOTTERY_PLAY_MANAGEMENT_PAGE_SUCCESS = 'INIT_LOTTERY_PLAY_MANAGEMENT_PAGE_SUCCESS';
export const INIT_LOTTERY_PLAY_MANAGEMENT_PAGE_FAILED = 'INIT_LOTTERY_PLAY_MANAGEMENT_PAGE_FAILED';
export const START_FETCH_LOTTERY_PLAY_MANAGEMENT_PAGE_PLAYS ='START_FETCH_LOTTERY_PLAY_MANAGEMENT_PAGE_PLAYS';
export const FETCH_LOTTERY_PLAY_MANAGEMENT_PAGE_PLAYS_SUCCESS = 'FETCH_LOTTERY_PLAY_MANAGEMENT_PAGE_PLAYS_SUCCESS';
export const FETCH_LOTTERY_PLAY_MANAGEMENT_PAGE_PLAYS_FAILED = 'FETCH_LOTTERY_PLAY_MANAGEMENT_PAGE_PLAYS_FAILED';
export const SET_LOTTERY_PLAY_MANAGEMENT_PAGE_LOTTERY_CLASS_ID = 'SET_LOTTERY_PLAY_MANAGEMENT_PAGE_LOTTERY_CLASS_ID';

// 招商帳戶設定
export const START_FETCH_ZHAO_SHANG_ACCOUNTS = 'START_FETCH_ZHAO_SHANG_ACCOUNTS';
export const FETCH_ZHAO_SHANG_ACCOUNTS_SUCCESS = 'FETCH_ZHAO_SHANG_ACCOUNTS_SUCCESS';
export const FETCH_ZHAO_SHANG_ACCOUNTS_FAILED = 'FETCH_ZHAO_SHANG_ACCOUNTS_FAILED';

export const START_CREATE_ZHAO_SHANG_ACCOUNT = 'START_CREATE_ZHAO_SHANG_ACCOUNT';
export const CREATE_ZHAO_SHANG_ACCOUNT_SUCCESS = 'CREATE_ZHAO_SHANG_ACCOUNT_SUCCESS';
export const CREATE_ZHAO_SHANG_ACCOUNT_FAILED = 'CREATE_ZHAO_SHANG_ACCOUNT_FAILED';

export const SET_LOTTERY_PLAY_CLASS_OPTIONS = 'SET_LOTTERY_PLAY_CLASS_OPTIONS';
export const SET_LOTTERY_PLAY_TABS = 'SET_LOTTERY_PLAY_TABS';
export const SET_LOTTERY_DRAWING_CLASS_OPTIONS = 'SET_LOTTERY_DRAWING_CLASS_OPTIONS';
export const SET_LOTTERY_DRAWING_TABS = 'SET_LOTTERY_DRAWING_TABS';
export const SET_LOTTERY_DRAWING_INTERVAL = 'SET_LOTTERY_DRAWING_INTERVAL';
export const START_UPDATE_DRAWING_INTERVAL = 'START_UPDATE_DRAWING_INTERVAL';
export const STOP_UPDATE_DRAWING_INTERVAL = 'STOP_UPDATE_DRAWING_INTERVAL';

// drawings
export const START_INIT_LOTTERY_DRAWING_ISSUE_PAGE = 'START_INIT_LOTTERY_DRAWING_ISSUE_PAGE';
export const INIT_LOTTERY_DRAWING_ISSUE_PAGE_SUCCESS = 'INIT_LOTTERY_DRAWING_ISSUE_PAGE_SUCCESS';
export const INIT_LOTTERY_DRAWING_ISSUE_PAGE_FAILED = 'INIT_LOTTERY_DRAWING_ISSUE_PAGE_FAILED';

export const START_FETCH_LOTTERY_DRAWINGS = 'START_FETCH_LOTTERY_DRAWINGS';
export const FETCH_LOTTERY_DRAWINGS_SUCCESS = 'FETCH_LOTTERY_DRAWINGS_SUCCESS';
export const FETCH_LOTTERY_DRAWINGS_FAILED = 'FETCH_LOTTERY_DRAWINGS_FAILED';

export const START_STOP_LOTTERY_DRAWING = 'START_STOP_LOTTERY_DRAWING';
export const STOP_LOTTERY_DRAWING_SUCCESS = 'STOP_LOTTERY_DRAWING_SUCCESS';
export const STOP_LOTTERY_DRAWING_FAILED = 'STOP_LOTTERY_DRAWING_FAILED';

export const START_CANCEL_LOTTERY_DRAWING = 'START_CANCEL_LOTTERY_DRAWING';
export const CANCEL_LOTTERY_DRAWING_SUCCESS = 'CANCEL_LOTTERY_DRAWING_SUCCESS';
export const CANCEL_LOTTERY_DRAWING_FAILED = 'CANCEL_LOTTERY_DRAWING_FAILED';

export const START_FETCH_LOTTERY_DRAWING_DETAIL = 'START_FETCH_LOTTERY_DRAWING_DETAIL';
export const FETCH_LOTTERY_DRAWING_DETAIL_SUCCESS = 'FETCH_LOTTERY_DRAWING_DETAIL_SUCCESS';
export const FETCH_LOTTERY_DRAWING_DETAIL_FAILED = 'FETCH_LOTTERY_DRAWING_DETAIL_FAILED';

export const START_FETCH_LOTTERY_DRAWING_BETTINGS_COUNT = 'START_FETCH_LOTTERY_DRAWING_BETTINGS_COUNT';
export const FETCH_LOTTERY_DRAWING_BETTINGS_COUNT_SUCCESS = 'FETCH_LOTTERY_DRAWING_BETTINGS_COUNT_SUCCESS';
export const FETCH_LOTTERY_DRAWING_BETTINGS_COUNT_FAILED = 'FETCH_LOTTERY_DRAWING_BETTINGS_COUNT_FAILED';

export const START_UPDATE_LOTTERY_DRAWING_OPENCODE = 'START_UPDATE_LOTTERY_DRAWING_OPENCODE';
export const UPDATE_LOTTERY_DRAWING_OPENCODE_SUCCESS = 'UPDATE_LOTTERY_DRAWING_OPENCODE_SUCCESS';
export const UPDATE_LOTTERY_DRAWING_OPENCODE_FAILED = 'UPDATE_LOTTERY_DRAWING_OPENCODE_FAILED';

// auto update drawing 
export const START_UPDATE_LOTTERY_DRAWING_INTERVAL = 'START_UPDATE_LOTTERY_DRAWING_INTERVAL';
export const STOP_UPDATE_LOTTERY_DRAWING_INTERVAL = 'STOP_UPDATE_LOTTERY_DRAWING_INTERVAL';

export const START_INIT_LOTTERY_MANAGEMENT_PAGE = 'START_INIT_LOTTERY_MANAGEMENT_PAGE';
export const INIT_LOTTERY_MANAGEMENT_PAGE_SUCCESS = 'INIT_LOTTERY_MANAGEMENT_PAGE_SUCCESS';
export const INIT_LOTTERY_MANAGEMENT_PAGE_FAILED = 'INIT_LOTTERY_MANAGEMENT_PAGE_FAILED';

export const START_INIT_LOTTERY_CLASS_MANAGEMENT_PAGE = 'START_INIT_LOTTERY_CLASS_MANAGEMENT_PAGE';
export const INIT_LOTTERY_CLASS_MANAGEMENT_PAGE_SUCCESS = 'INIT_LOTTERY_CLASS_MANAGEMENT_PAGE_SUCCESS';
export const INIT_LOTTERY_CLASS_MANAGEMENT_PAGE_FAILED = 'INIT_LOTTERY_CLASS_MANAGEMENT_PAGE_FAILED';
export const START_INIT_LOTTERY_DRAWING_MANAGEMENT_PAGE = 'START_INIT_LOTTERY_DRAWING_MANAGEMENT_PAGE';
export const INIT_LOTTERY_DRAWING_MANAGEMENT_PAGE_SUCCESS = 'INIT_LOTTERY_DRAWING_MANAGEMENT_PAGE_SUCCESS';
export const INIT_LOTTERY_DRAWING_MANAGEMENT_PAGE_FAILED = 'INIT_LOTTERY_DRAWING_MANAGEMENT_PAGE_FAILED';

//Auth
export const START_LOGIN = 'START_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const START_LOGOUT = 'START_LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

export const START_CHECK_AUTH = 'START_CHECK_AUTH';
export const CHECK_AUTH_SUCCESS = 'CHECK_AUTH_SUCCESS';
export const CHECK_AUTH_FAILED = 'CHECK_AUTH_FAILED';

//Lottery
export const START_INIT_LOTTERY_PLAY_BONUS_XINYONG_MANAGEMENT_PAGE = 'START_INIT_LOTTERY_PLAY_BONUS_XINYONG_MANAGEMENT_PAGE';
export const INIT_LOTTERY_PLAY_BONUS_XINYONG_MANAGEMENT_PAGE_SUCCESS = 'INIT_LOTTERY_PLAY_BONUS_XINYONG_MANAGEMENT_PAGE_SUCCESS';
export const INIT_LOTTERY_PLAY_BONUS_XINYONG_MANAGEMENT_PAGE_FAILED = 'INIT_LOTTERY_PLAY_BONUS_XINYONG_MANAGEMENT_PAGE_FAILED';
export const SET_LOTTERY_PLAY_BONUS_XINYONG_MANAGEMENT_PAGE_LOTTERY_OPTIONS = 'SET_LOTTERY_PLAY_BONUS_XINYONG_MANAGEMENT_PAGE_LOTTERY_OPTIONS';

export const START_INIT_LOTTERY_PLAY_BONUS_STANDARD_MANAGEMENT_PAGE = 'START_INIT_LOTTERY_PLAY_BONUS_STANDARD_MANAGEMENT_PAGE';
export const INIT_LOTTERY_PLAY_BONUS_STANDARD_MANAGEMENT_PAGE_SUCCESS = 'INIT_LOTTERY_PLAY_BONUS_STANDARD_MANAGEMENT_PAGE_SUCCESS';
export const INIT_LOTTERY_PLAY_BONUS_STANDARD_MANAGEMENT_PAGE_FAILED = 'INIT_LOTTERY_PLAY_BONUS_STANDARD_MANAGEMENT_PAGE_FAILED';
export const START_FETCH_LOTTERY_PLAY_BONUS_STANDARD_MANAGEMENT_PAGE_PLAYS ='START_FETCH_LOTTERY_PLAY_BONUS_STANDARD_MANAGEMENT_PAGE_PLAYS';
export const FETCH_LOTTERY_PLAY_BONUS_STANDARD_MANAGEMENT_PAGE_PLAYS_SUCCESS = 'FETCH_LOTTERY_PLAY_BONUS_STANDARD_MANAGEMENT_PAGE_PLAYS_SUCCESS';
export const FETCH_LOTTERY_PLAY_BONUS_STANDARD_MANAGEMENT_PAGE_PLAYS_FAILED = 'FETCH_LOTTERY_PLAY_BONUS_STANDARD_MANAGEMENT_PAGE_PLAYS_FAILED';
export const SET_LOTTERY_PLAY_BONUS_STANDARD_MANAGEMENT_PAGE_LOTTERY_CLASS_ID = 'SET_LOTTERY_PLAY_BONUS_STANDARD_MANAGEMENT_PAGE_LOTTERY_CLASS_ID';
// TODO: 之後改用 url 帶 query 的方法完成後，要刪掉 RESET_LOTTERY_CLASS_ID
export const RESET_LOTTERY_CLASS_ID = 'RESET_LOTTERY_CLASS_ID';

export const START_INIT_LOTTERY_SPECIAL_MANAGEMENT_PAGE = 'START_INIT_LOTTERY_SPECIAL_MANAGEMENT_PAGE';
export const INIT_LOTTERY_SPECIAL_MANAGEMENT_PAGE_SUCCESS = 'INIT_LOTTERY_SPECIAL_MANAGEMENT_PAGE_SUCCESS';
export const INIT_LOTTERY_SPECIAL_MANAGEMENT_PAGE_FAILED = 'INIT_LOTTERY_SPECIAL_MANAGEMENT_PAGE_FAILED';

// Record selected lottery drawing data
export const SET_SELECTED_LOTTERY_DRAWING = 'SET_SELECTED_LOTTERY_DRAWING';
export const REMOVE_SELECTED_LOTTERY_DRAWING = 'REMOVE_SELECTED_LOTTERY_DRAWING';

// 會員獎金規則
export const START_INIT_USER_BONUS_RULES_MANAGEMENT_PAGE = 'START_INIT_USER_BONUS_RULES_MANAGEMENT_PAGE';
export const INIT_USER_BONUS_RULES_MANAGEMENT_PAGE_SUCCESS = 'INIT_USER_BONUS_RULES_MANAGEMENT_PAGE_SUCCESS';
export const INIT_USER_BONUS_RULES_MANAGEMENT_PAGE_FAILED = 'INIT_USER_BONUS_RULES_MANAGEMENT_PAGE_FAILED';

// Cash system
export const START_FETCH_CASH_SYSTEM_BANK_DEPOSIT = 'START_FETCH_CASH_SYSTEM_BANK_DEPOSIT';
export const FETCH_CASH_SYSTEM_BANK_DEPOSIT_SUCCESS = 'FETCH_CASH_SYSTEM_BANK_DEPOSIT_SUCCESS';
export const FETCH_CASH_SYSTEM_BANK_DEPOSIT_FAILED = 'FETCH_CASH_SYSTEM_BANK_DEPOSIT_FAILED';

// Cash system - Hierarchical Management
export const START_INIT_CASH_SYSTEM_HIERARCHICAL_MANAGEMENT_PAGE = 'START_INIT_CASH_SYSTEM_HIERARCHICAL_MANAGEMENT_PAGE';
export const INIT_CASH_SYSTEM_HIERARCHICAL_MANAGEMENT_PAGE_SUCCESS = 'INIT_CASH_SYSTEM_HIERARCHICAL_MANAGEMENT_PAGE_SUCCESS';
export const INIT_CASH_SYSTEM_HIERARCHICAL_MANAGEMENT_PAGE_FAILED = 'INIT_CASH_SYSTEM_HIERARCHICAL_MANAGEMENT_PAGE_FAILED';
export const START_REFRESH_CASH_SYSTEM_HIERARCHICAL_MANAGEMENT_NORMAL_LEVELS = 'START_REFRESH_CASH_SYSTEM_HIERARCHICAL_MANAGEMENT_NORMAL_LEVELS';
export const REFRESH_CASH_SYSTEM_HIERARCHICAL_MANAGEMENT_NORMAL_LEVELS_SUCCESS = 'REFRESH_CASH_SYSTEM_HIERARCHICAL_MANAGEMENT_NORMAL_LEVELS_SUCCESS';
export const REFRESH_CASH_SYSTEM_HIERARCHICAL_MANAGEMENT_NORMAL_LEVELS_FAILED = 'REFRESH_CASH_SYSTEM_HIERARCHICAL_MANAGEMENT_NORMAL_LEVELS_FAILED';
export const START_FETCH_CASH_SYSTEM_HIERARCHICAL_MANAGEMENT_USER_LEVEL = 'START_FETCH_CASH_SYSTEM_HIERARCHICAL_MANAGEMENT_USER_LEVEL';
export const FETCH_CASH_SYSTEM_HIERARCHICAL_MANAGEMENT_USER_LEVEL_SUCCESS = 'FETCH_CASH_SYSTEM_HIERARCHICAL_MANAGEMENT_USER_LEVEL_SUCCESS';
export const FETCH_CASH_SYSTEM_HIERARCHICAL_MANAGEMENT_USER_LEVEL_FAILED = 'FETCH_CASH_SYSTEM_HIERARCHICAL_MANAGEMENT_USER_LEVEL_FAILED';

export const START_UPDATE_FINANCE_NORMAL_LEVELS = 'START_UPDATE_FINANCE_NORMAL_LEVELS';
export const UPDATE_FINANCE_NORMAL_LEVELS_SUCCESS = 'UPDATE_FINANCE_NORMAL_LEVELS_SUCCESS';
export const UPDATE_FINANCE_NORMAL_LEVELS_FAILED = 'UPDATE_FINANCE_NORMAL_LEVELS_FAILED';

export const START_UPDATE_FINANCE_SPECIAL_LEVELS = 'START_UPDATE_FINANCE_SPECIAL_LEVELS';
export const UPDATE_FINANCE_SPECIAL_LEVELS_SUCCESS = 'UPDATE_FINANCE_SPECIAL_LEVELS_SUCCESS';
export const UPDATE_FINANCE_SPECIAL_LEVELS_FAILED = 'UPDATE_FINANCE_SPECIAL_LEVELS_FAILED';

export const START_FETCH_USER_LEVEL_LOGS = 'START_FETCH_USER_LEVEL_LOGS';
export const FETCH_USER_LEVEL_LOGS_SUCCESS = 'FETCH_USER_LEVEL_LOGS_SUCCESS';
export const FETCH_USER_LEVEL_LOGS_FAILED = 'FETCH_USER_LEVEL_LOGS_FAILED';

// Team
export const START_FETCH_TEAM_CHILDREN = 'START_FETCH_TEAM_CHILDREN';
export const FETCH_TEAM_CHILDREN_SUCCESS = 'FETCH_TEAM_CHILDREN_SUCCESS';
export const FETCH_TEAM_CHILDREN_FAILED = 'FETCH_TEAM_CHILDREN_FAILED';
export const START_FETCH_TEAM_STATS = 'START_FETCH_TEAM_STATS';
export const FETCH_TEAM_STATS_SUCCESS = 'FETCH_TEAM_STATS_SUCCESS';
export const FETCH_TEAM_STATS_FAILED = 'FETCH_TEAM_STATS_FAILED';
export const START_ENABLE_TEAM_ACCOUNT = 'START_ENABLE_TEAM_ACCOUNT';
export const ENABLE_TEAM_ACCOUNT_SUCCESS = 'ENABLE_TEAM_ACCOUNT_SUCCESS';
export const ENABLE_TEAM_ACCOUNT_FAILED = 'ENABLE_TEAM_ACCOUNT_FAILED';
export const START_DISABLE_TEAM_ACCOUNT = 'START_DISABLE_TEAM_ACCOUNT';
export const DISABLE_TEAM_ACCOUNT_SUCCESS = 'DISABLE_TEAM_ACCOUNT_SUCCESS';
export const DISABLE_TEAM_ACCOUNT_FAILED = 'DISABLE_TEAM_ACCOUNT_FAILED';
export const START_ENABLE_TEAM_BETTING = 'START_ENABLE_TEAM_BETTING';
export const ENABLE_TEAM_BETTING_SUCCESS = 'ENABLE_TEAM_BETTING_SUCCESS';
export const ENABLE_TEAM_BETTING_FAILED = 'ENABLE_TEAM_BETTING_FAILED';
export const START_DISABLE_TEAM_BETTING = 'START_DISABLE_TEAM_BETTING';
export const DISABLE_TEAM_BETTING_SUCCESS = 'DISABLE_TEAM_BETTING_SUCCESS';
export const DISABLE_TEAM_BETTING_FAILED = 'DISABLE_TEAM_BETTING_FAILED';
export const START_ENABLE_TEAM_DEPOSIT = 'START_ENABLE_TEAM_DEPOSIT';
export const ENABLE_TEAM_DEPOSIT_SUCCESS = 'ENABLE_TEAM_DEPOSIT_SUCCESS';
export const ENABLE_TEAM_DEPOSIT_FAILED = 'ENABLE_TEAM_DEPOSIT_FAILED';
export const START_DISABLE_TEAM_DEPOSIT = 'START_DISABLE_TEAM_DEPOSIT';
export const DISABLE_TEAM_DEPOSIT_SUCCESS = 'DISABLE_TEAM_DEPOSIT_SUCCESS';
export const DISABLE_TEAM_DEPOSIT_FAILED = 'DISABLE_TEAM_DEPOSIT_FAILED';
export const START_ENABLE_TEAM_FUNDS = 'START_ENABLE_TEAM_FUNDS';
export const ENABLE_TEAM_FUNDS_SUCCESS = 'ENABLE_TEAM_FUNDS_SUCCESS';
export const ENABLE_TEAM_FUNDS_FAILED = 'ENABLE_TEAM_FUNDS_FAILED';
export const START_DISABLE_TEAM_FUNDS = 'START_DISABLE_TEAM_FUNDS';
export const DISABLE_TEAM_FUNDS_SUCCESS = 'DISABLE_TEAM_FUNDS_SUCCESS';
export const DISABLE_TEAM_FUNDS_FAILED = 'DISABLE_TEAM_FUNDS_FAILED';
export const START_ENABLE_TEAM_SUBORDINATE_CREATION = 'START_ENABLE_TEAM_SUBORDINATE_CREATION';
export const ENABLE_TEAM_SUBORDINATE_CREATION_SUCCESS = 'ENABLE_TEAM_SUBORDINATE_CREATION_SUCCESS';
export const ENABLE_TEAM_SUBORDINATE_CREATION_FAILED = 'ENABLE_TEAM_SUBORDINATE_CREATION_FAILED';
export const START_DISABLE_TEAM_SUBORDINATE_CREATION = 'START_DISABLE_TEAM_SUBORDINATE_CREATION';
export const DISABLE_TEAM_SUBORDINATE_CREATION_SUCCESS = 'DISABLE_TEAM_SUBORDINATE_CREATION_SUCCESS';
export const DISABLE_TEAM_SUBORDINATE_CREATION_FAILED = 'DISABLE_TEAM_SUBORDINATE_CREATION_FAILED';
export const START_ENABLE_TEAM_WITHDRAW = 'START_ENABLE_TEAM_WITHDRAW';
export const ENABLE_TEAM_WITHDRAW_SUCCESS = 'ENABLE_TEAM_WITHDRAW_SUCCESS';
export const ENABLE_TEAM_WITHDRAW_FAILED = 'ENABLE_TEAM_WITHDRAW_FAILED';
export const START_DISABLE_TEAM_WITHDRAW = 'START_DISABLE_TEAM_WITHDRAW';
export const DISABLE_TEAM_WITHDRAW_SUCCESS = 'DISABLE_TEAM_WITHDRAW_SUCCESS';
export const DISABLE_TEAM_WITHDRAW_FAILED = 'DISABLE_TEAM_WITHDRAW_FAILED';
// Team - Member
export const START_ENABLE_TEAM_MEMBER_ACCOUNT = 'START_ENABLE_TEAM_MEMBER_ACCOUNT';
export const ENABLE_TEAM_MEMBER_ACCOUNT_SUCCESS = 'ENABLE_TEAM_MEMBER_ACCOUNT_SUCCESS';
export const ENABLE_TEAM_MEMBER_ACCOUNT_FAILED = 'ENABLE_TEAM_MEMBER_ACCOUNT_FAILED';
export const START_ENABLE_TEAM_MEMBER_BETTING = 'START_ENABLE_TEAM_MEMBER_BETTING';
export const ENABLE_TEAM_MEMBER_BETTING_SUCCESS = 'ENABLE_TEAM_MEMBER_BETTING_SUCCESS';
export const ENABLE_TEAM_MEMBER_BETTING_FAILED = 'ENABLE_TEAM_MEMBER_BETTING_FAILED';
export const START_ENABLE_TEAM_MEMBER_DEPOSIT = 'START_ENABLE_TEAM_MEMBER_DEPOSIT';
export const ENABLE_TEAM_MEMBER_DEPOSIT_SUCCESS = 'ENABLE_TEAM_MEMBER_DEPOSIT_SUCCESS';
export const ENABLE_TEAM_MEMBER_DEPOSIT_FAILED = 'ENABLE_TEAM_MEMBER_DEPOSIT_FAILED';
export const START_ENABLE_TEAM_MEMBER_FUNDS = 'START_ENABLE_TEAM_MEMBER_FUNDS';
export const ENABLE_TEAM_MEMBER_FUNDS_SUCCESS = 'ENABLE_TEAM_MEMBER_FUNDS_SUCCESS';
export const ENABLE_TEAM_MEMBER_FUNDS_FAILED = 'ENABLE_TEAM_MEMBER_FUNDS_FAILED';
export const START_ENABLE_TEAM_MEMBER_WITHDRAW = 'START_ENABLE_TEAM_MEMBER_WITHDRAW';
export const ENABLE_TEAM_MEMBER_WITHDRAW_SUCCESS = 'ENABLE_TEAM_MEMBER_WITHDRAW_SUCCESS';
export const ENABLE_TEAM_MEMBER_WITHDRAW_FAILED = 'ENABLE_TEAM_MEMBER_WITHDRAW_FAILED';
// Withdrawal - Message
export const START_FETCH_USER_WITHDRAWAL_MESSAGE = 'START_FETCH_USER_WITHDRAWAL_MESSAGE';
export const FETCH_USER_WITHDRAWAL_MESSAGE_SUCCESS = 'FETCH_USER_WITHDRAWAL_MESSAGE_SUCCESS';
export const FETCH_USER_WITHDRAWAL_MESSAGE_FAILED = 'FETCH_USER_WITHDRAWAL_MESSAGE_FAILED';
export const START_UPDATE_USER_WITHDRAWAL_MESSAGE = 'START_UPDATE_USER_WITHDRAWAL_MESSAGE';
export const UPDATE_USER_WITHDRAWAL_MESSAGE_SUCCESS = 'UPDATE_USER_WITHDRAWAL_MESSAGE_SUCCESS';
export const UPDATE_USER_WITHDRAWAL_MESSAGE_FAILED = 'UPDATE_USER_WITHDRAWAL_MESSAGE_FAILED';
export const START_DELETE_USER_WITHDRAWAL_MESSAGE = 'START_DELETE_USER_WITHDRAWAL_MESSAGE';
export const DELETE_USER_WITHDRAWAL_MESSAGE_SUCCESS = 'DELETE_USER_WITHDRAWAL_MESSAGE_SUCCESS';
export const DELETE_USER_WITHDRAWAL_MESSAGE_FAILED = 'DELETE_USER_WITHDRAWAL_MESSAGE_FAILED';

// BankCard black list
export const START_FETCH_BANK_CARD_BLACK_LIST = 'START_FETCH_BANK_CARD_BLACK_LIST';
export const FETCH_BANK_CARD_BLACK_LIST_SUCCESS = 'FETCH_BANK_CARD_BLACK_LIST_SUCCESS';
export const FETCH_BANK_CARD_BLACK_LIST_FAILED = 'FETCH_BANK_CARD_BLACK_LIST_FAILED';
export const START_ADD_BANK_CARDS_TO_BLACK_LIST = 'START_ADD_BANK_CARDS_TO_BLACK_LIST';
export const ADD_BANK_CARDS_TO_BLACK_LIST_SUCCESS = 'ADD_BANK_CARDS_TO_BLACK_LIST_SUCCESS';
export const ADD_BANK_CARDS_TO_BLACK_LIST_FAILED = 'ADD_BANK_CARDS_TO_BLACK_LIST_FAILED';
export const START_REMOVE_BANK_CARD_FROM_BLACK_LIST = 'START_REMOVE_BANK_CARD_FROM_BLACK_LIST';
export const REMOVE_BANK_CARD_FROM_BLACK_LIST_SUCCESS = 'REMOVE_BANK_CARD_FROM_BLACK_LIST_SUCCESS';
export const REMOVE_BANK_CARD_FROM_BLACK_LIST_FAILED = 'REMOVE_BANK_CARD_FROM_BLACK_LIST_FAILED';

// Finance Level
export const START_FETCH_FINANCE_LEVELS = 'START_FETCH_FINANCE_LEVELS';
export const FETCH_FINANCE_LEVELS_SUCCESS = 'FETCH_FINANCE_LEVELS_SUCCESS';
export const FETCH_FINANCE_LEVELS_FAILED = 'FETCH_FINANCE_LEVELS_FAILED';
export const START_FETCH_FINANCE_LEVEL_USERS = 'START_FETCH_FINANCE_LEVEL_USERS';
export const FETCH_FINANCE_LEVEL_USERS_SUCCESS = 'FETCH_FINANCE_LEVEL_USERS_SUCCESS';
export const FETCH_FINANCE_LEVEL_USERS_FAILED = 'FETCH_FINANCE_LEVEL_USERS_FAILED';
