module.exports = {
	TOPIC_OF_FETCH_LATEST_DRAWING_COMMAND: "drawing.command.fetch",
	TOPIC_OF_DRAWING_REPLY_EVENT: "drawing.event.reply",
	TOPIC_OF_OPEN_BETTINGS_COMMAND: "betting.command.open",
	TOPIC_OF_GRANT_COMMISSIONS_COMMAND: "commission.command.grant",
	TOPIC_OF_TERMINATE_TRACES_COMMAND: "trace.command.terminate",
	TOPIC_OF_CANCEL_BETTINGS_COMMAND: "betting.command.cancel",
	TOPIC_OF_RENEW_BETTINGS_COMMAND: "betting.command.renew",
	TOPIC_OF_OPEN_BETTINGS_REPLY_EVENT: "betting.event.reply",
	TOPIC_OF_CANCEL_DUPLICATED_DRAWING_COMMAND: "duplicated-drawing.command.cancel",
	TOPIC_OF_CANCEL_DUPLICATED_DRAWING_REPLY_EVENT: "duplicated-drawing.event.canceled",
	TOPIC_OF_DIVIDEND_STATS_COMMAND: "dividend.command.stats",
	TOPIC_OF_DIVIDEND_STATS_REPLY_EVENT: "dividend.event.reply",
	TOPIC_OF_CLOSE_LOTTERY_FOR_EARLY_OPENED_DRAWING_COMMAND: "lottery.command.close",
	TOPIC_OF_CLOSE_LOTTERY_FOR_EARLY_OPENED_DRAWING_REPLY_EVENT: "lottery.event.reply",
	TOPIC_OF_DIVIDEND_TRANSFER_COMMAND: "dividend.command.transfer",
	TOPIC_OF_DIVIDEND_TRANSFER_REPLY_EVENT: "dividend.event.transfered",
	TOPIC_OF_GRANT_ZHAOSHANG_DIVIDENDS_COMMAND: "zhaoshang-dividends.command.grant",
	TOPIC_OF_APPLY_AUTO_REMIT_COMMAND: "auto-remit.command.apply",
	TOPIC_OF_AUTO_REMIT_REPLY_EVENT: "auto-remit.event.reply",
	TOPIC_OF_REMIT_USING_BANK_COMMAND: "bank.command.remit",
	TOPIC_OF_REMIT_USING_THIRD_PARTY_COMMAND: "third-party.command.remit",
	TOPIC_OF_TEAM_BONUS_STATS_COMMAND: "team.command.bonus-stats",
	TOPIC_OF_TEAM_STATS_COMMAND: "team.command.stats",
	TOPIC_OF_TEAM_STATS_REPLY_EVENT: "team.event.reply",
};
