const FIVE_MINUTES = 300;
const ONE_MINUTE = 60;

const LAST_OPENED_AND_FUTURE_DRAWINGS_TTL = FIVE_MINUTES;
const PLAY_CLASSES_TTL = FIVE_MINUTES;
const PLAYS_TTL = FIVE_MINUTES;
const PLAY_CONDITIONS_TTL = FIVE_MINUTES;
const LOTTERIES_TTL = FIVE_MINUTES;
const LOTTERY_CLASSES_TTL = FIVE_MINUTES;
const LOTTERY_PLAYS_TTL = FIVE_MINUTES;
const USER_ONLINE_STATUS_TTL = ONE_MINUTE;
const SECURITY_QUESTIONS_TTL = FIVE_MINUTES;

module.exports = {
	LAST_OPENED_AND_FUTURE_DRAWINGS_TTL,
	PLAY_CLASSES_TTL,
	PLAYS_TTL,
	PLAY_CONDITIONS_TTL,
	LOTTERIES_TTL,
	LOTTERY_CLASSES_TTL,
	LOTTERY_PLAYS_TTL,
	USER_ONLINE_STATUS_TTL,
	SECURITY_QUESTIONS_TTL,
};
