
//notify handling
import { notifyHandlingActions, } from '../../../lib/notify-handler';
export const { CATCH_NOTIFY_HANDLING, } = notifyHandlingActions;

// Application
export const START_INITIALIZE_APPLICATION = 'START_INITIALIZE_APPLICATION';
export const INITIALIZE_APPLICATION_SUCCESS = 'INITIALIZE_APPLICATION_SUCCESS';
export const INITIALIZE_APPLICATION_FAILED = 'INITIALIZE_APPLICATION_FAILED';

// Login
export const START_LOGIN = 'START_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

// Login via totp
export const START_LOGIN_VIA_GOOGLE_TOTP = 'START_LOGIN_VIA_GOOGLE_TOTP';
export const LOGIN_VIA_GOOGLE_TOTP_SUCCESS = 'LOGIN_VIA_GOOGLE_TOTP_SUCCESS';
export const LOGIN_VIA_GOOGLE_TOTP_FAILED = 'LOGIN_VIA_GOOGLE_TOTP_FAILED';

// Fetch Captcha
export const START_FETCH_CAPTCHA = 'START_FETCH_CAPTCHA';
export const FETCH_CAPTCHA_SUCCESS = 'FETCH_CAPTCHA_SUCCESS';
export const FETCH_CAPTCHA_FAILED = 'FETCH_CAPTCHA_FAILED';
// Check Captcha
export const START_CHECK_CAPTCHA = 'START_CHECK_CAPTCHA';
export const CHECK_CAPTCHA_SUCCESS = 'CHECK_CAPTCHA_SUCCESS';
export const CHECK_CAPTCHA_FAILED = 'CHECK_CAPTCHA_FAILED';
// Captcha validate
export const SET_IS_CAPTCHA_VALIDATE = 'SET_IS_CAPTCHA_VALIDATE';

// Account Security
export const SET_IS_GEO_VALIDATION = 'SET_IS_GEO_VALIDATION';

// Geo validate
export const START_GEO_VALIDATE_WITH_PAYER = 'START_GEO_VALIDATE_WITH_PAYER';
export const GEO_VALIDATE_WITH_PAYER_SUCCESS = 'GEO_VALIDATE_WITH_PAYER_SUCCESS';
export const GEO_VALIDATE_WITH_PAYER_FAILED = 'GEO_VALIDATE_WITH_PAYER_FAILED';

export const START_LOGOUT = 'START_LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

// Auth
export const START_CHECK_AUTH = 'START_CHECK_AUTH';
export const CHECK_AUTH_SUCCESS = 'CHECK_AUTH_SUCCESS';
export const CHECK_AUTH_FAILED = 'CHECK_AUTH_FAILED';

export const START_UPDATE_DEFAULT_PASSWORD = 'START_UPDATE_DEFAULT_PASSWORD';
export const UPDATE_DEFAULT_PASSWORD_SUCCESS = 'UPDATE_DEFAULT_PASSWORD_SUCCESS';
export const UPDATE_DEFAULT_PASSWORD_FAILED = 'UPDATE_DEFAULT_PASSWORD_FAILED';
// Reset Password
export const START_FETCH_PASSWORD_RESET_METHODS = 'START_FETCH_PASSWORD_RESET_METHODS';
export const FETCH_PASSWORD_RESET_METHODS_SUCCESS = 'FETCH_PASSWORD_RESET_METHODS_SUCCESS';
export const FETCH_PASSWORD_RESET_METHODS_FAILED = 'FETCH_PASSWORD_RESET_METHODS_FAILED';
export const START_RESET_PASSWORD_VIA_SECURITY_QUESTIONS = 'START_RESET_PASSWORD_VIA_SECURITY_QUESTIONS';
export const RESET_PASSWORD_VIA_SECURITY_QUESTIONS_SUCCESS = 'START_RESET_PASSWORD_VIA_SECURITY_QUESTIONS_SUCCESS';
export const RESET_PASSWORD_VIA_SECURITY_QUESTIONS_FAILED = 'START_RESET_PASSWORD_VIA_SECURITY_QUESTIONS_FAILED';
export const START_RESET_PASSWORD_VIA_GOOGLE_TOTP = 'START_RESET_PASSWORD_VIA_GOOGLE_TOTP';
export const RESET_PASSWORD_VIA_GOOGLE_TOTP_SUCCESS = 'RESET_PASSWORD_VIA_GOOGLE_TOTP_SUCCESS';
export const RESET_PASSWORD_VIA_GOOGLE_TOTP_FAILED = 'RESET_PASSWORD_VIA_GOOGLE_TOTP_FAILED';

// User
export const START_FETCH_USER = 'START_FETCH_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED';
export const START_CREATE_CHILDREN_USER = 'START_CREATE_CHILDREN_USER';
export const CREATE_CHILDREN_USER_SUCCESS = 'CREATE_CHILDREN_USER_SUCCESS';
export const CREATE_CHILDREN_USER_FAILED = 'CREATE_CHILDREN_USER_FAILED';
export const START_UPDATE_USER_NICKNAME = 'START_UPDATE_USER_NICKNAME';
export const UPDATE_USER_NICKNAME_SUCCESS = 'UPDATE_USER_NICKNAME_SUCCESS';
export const UPDATE_USER_NICKNAME_FAILED = 'UPDATE_USER_NICKNAME_FAILED';
export const START_UPDATE_USER_GREETING = 'START_UPDATE_USER_GREETING';
export const UPDATE_USER_GREETING_SUCCESS = 'UPDATE_USER_GREETING_SUCCESS';
export const UPDATE_USER_GREETING_FAILED = 'UPDATE_USER_GREETING_FAILED';
export const START_FETCH_CHILDREN_USERS = 'START_FETCH_CHILDREN_USERS';
export const FETCH_CHILDREN_USERS_SUCCESS = 'FETCH_CHILDREN_USERS_SUCCESS';
export const FETCH_CHILDREN_USERS_FAILED = 'FETCH_CHILDREN_USERS_FAILED';
export const SET_IS_USER_VALIDATED_BY_PASSWORD = 'SET_IS_USER_VALIDATED_BY_PASSWORD';
export const START_TRANSFER_TO_USER = 'START_TRANSFER_TO_USER';
export const TRANSFER_TO_USER_SUCCESS = 'TRANSFER_TO_USER_SUCCESS';
export const TRANSFER_TO_USER_FAILED = 'TRANSFER_TO_USER_FAILED';
export const START_UPDATE_CHILDREN_USER = 'START_UPDATE_CHILDREN_USER';
export const UPDATE_CHILDREN_USER_SUCCESS = 'UPDATE_CHILDREN_USER_SUCCESS';
export const UPDATE_CHILDREN_USER_FAILED = 'UPDATE_CHILDREN_USER_FAILED';

// User Lottery Collections
export const START_FETCH_MY_LOTTERY_COLLECTIONS = 'START_FETCH_MY_LOTTERY_COLLECTIONS';
export const FETCH_MY_LOTTERY_COLLECTIONS_SUCCESS = 'FETCH_MY_LOTTERY_COLLECTIONS_SUCCESS';
export const FETCH_MY_LOTTERY_COLLECTIONS_FAILED = 'FETCH_MY_LOTTERY_COLLECTIONS_FAILED';
export const START_UPDATE_MY_LOTTERY_COLLECTIONS = 'START_UPDATE_MY_LOTTERY_COLLECTIONS';
export const UPDATE_MY_LOTTERY_COLLECTIONS_SUCCESS = 'UPDATE_MY_LOTTERY_COLLECTIONS_SUCCESS';
export const UPDATE_MY_LOTTERY_COLLECTIONS_FAILED = 'UPDATE_MY_LOTTERY_COLLECTIONS_FAILED';

// Lottery Class
export const START_FETCH_LOTTERY_CLASSES = 'START_FETCH_LOTTERY_CLASSES';
export const FETCH_LOTTERY_CLASSES_SUCCESS = 'FETCH_LOTTERY_CLASSES_SUCCESS';
export const FETCH_LOTTERY_CLASSES_FAILED = 'FETCH_LOTTERY_CLASSES_FAILED';

// Lottery
export const START_FETCH_LOTTERIES = 'START_FETCH_LOTTERIES';
export const FETCH_LOTTERIES_SUCCESS = 'FETCH_LOTTERIES_SUCCESS';
export const FETCH_LOTTERIES_FAILED = 'FETCH_LOTTERIES_FAILED';

// Betting
export const START_BET = 'START_BET';
export const BET_SUCCESS = 'BET_SUCCESS';
export const BET_FAILED = 'BET_FAILED';
export const ADD_BETTING = 'ADD_BETTING';
export const UPDATE_BETTING = 'UPDATE_BETTING';
export const SET_BETTINGS = 'SET_BETTINGS';
export const CLEAR_BETTING = 'CLEAR_BETTING';
export const CLEAR_BETTINGS = 'CLEAR_BETTINGS';
export const UPDATE_ALL_BETTINGS_AMOUNT_PER_BET = 'UPDATE_ALL_BETTINGS_AMOUNT_PER_BET';
export const RESET_STANDARD_BETTING_ELEMENT = 'RESET_STANDARD_BETTING_ELEMENT';
export const SET_BETTING_PROCESS_INIT = 'SET_BETTING_PROCESS_INIT';
export const SET_BETTING_PROCESS_NO_PASSWORD = 'SET_BETTING_PROCESS_NO_PASSWORD';
export const CANCEL_BET = 'CANCEL_BET';

// Betting Record
export const START_DISCARD_BETTING_RECORD = 'START_DISCARD_BETTING_RECORD';
export const DISCARD_BETTING_RECORD_SUCCESS = 'DISCARD_BETTING_RECORD_SUCCESS';
export const DISCARD_BETTING_RECORD_FAILED = 'DISCARD_BETTING_RECORD_FAILED';
export const START_FETCH_BETTING_RECORDS = 'START_FETCH_BETTING_RECORDS';
export const FETCH_BETTING_RECORDS_SUCCESS = 'FETCH_BETTING_RECORDS_SUCCESS';
export const FETCH_BETTING_RECORDS_FAILED = 'FETCH_BETTING_RECORDS_FAILED';
export const PREPEND_BETTING_RECORDS = 'PREPEND_BETTING_RECORDS';
export const START_FETCH_LATEST_BETTING_RECORDS = 'START_FETCH_LATEST_BETTING_RECORDS';
export const FETCH_LATEST_BETTING_RECORDS_SUCCESS = 'FETCH_LATEST_BETTING_RECORDS_SUCCESS';
export const FETCH_LATEST_BETTING_RECORDS_FAILED = 'FETCH_LATEST_BETTING_RECORDS_FAILED';

// Betting Record Detail
export const START_FETCH_BETTING_RECORD_DETAIL = 'START_FETCH_BETTING_RECORD_DETAIL';
export const FETCH_BETTING_RECORD_DETAIL_SUCESS = 'FETCH_BETTING_RECORD_DETAIL_SUCESS';
export const FETCH_BETTING_RECORD_DETAIL_FAILED = 'FETCH_BETTING_RECORD_DETAIL_FAILED';
export const RESET_BETTING_RECORDS_DETAILS = 'RESET_BETTING_RECORDS_DETAILS';

// Team Betting
export const START_FETCH_TEAM_BETTING_RECORDS = 'START_FETCH_TEAM_BETTING_RECORDS';
export const FETCH_TEAM_BETTING_RECORDS_SUCCESS = 'FETCH_TEAM_BETTING_RECORDS_SUCCESS';
export const FETCH_TEAM_BETTING_RECORDS_FAILED = 'FETCH_TEAM_BETTING_RECORDS_FAILED';

// Team Trace records
export const START_FETCH_TEAM_TRACE_RECORDS = 'START_FETCH_TEAM_TRACE_RECORDS';
export const FETCH_TEAM_TRACE_RECORDS_SUCCESS = 'FETCH_TEAM_TRACE_RECORDS_SUCCESS';
export const FETCH_TEAM_TRACE_RECORDS_FAILED = 'FETCH_TEAM_TRACE_RECORDS_FAILED';

// Team Trace Record
export const START_FETCH_TEAM_TRACE_RECORD_DETAIL = 'START_FETCH_TEAM_TRACE_RECORD_DETAIL';
export const FETCH_TEAM_TRACE_RECORD_DETAIL_SUCCESS = 'FETCH_TEAM_TRACE_RECORD_DETAIL_SUCCESS';
export const FETCH_TEAM_TRACE_RECORD_DETAIL_FAILED = 'FETCH_TEAM_TRACE_RECORD_DETAIL_FAILED';

// Team Trace Record Bettings
export const START_FETCH_TEAM_TRACE_RECORD_DETAIL_BETTINGS = 'START_FETCH_TEAM_TRACE_RECORD_DETAIL_BETTINGS';
export const FETCH_TEAM_TRACE_RECORD_DETAIL_BETTINGS_SUCCESS = 'FETCH_TEAM_TRACE_RECORD_DETAIL_BETTINGS_SUCCESS';
export const FETCH_TEAM_TRACE_RECORD_DETAIL_BETTINGS_FAILED = 'FETCH_TEAM_TRACE_RECORD_DETAIL_BETTINGS_FAILED';

// Trace
export const START_TRACE = 'START_TRACE';
export const TRACE_SUCCESS = 'TRACE_SUCCESS';
export const TRACE_FAILED = 'TRACE_FAILED';

// Trace Record
export const START_FETCH_TRACE_RECORDS = 'START_FETCH_TRACE_RECORDS';
export const FETCH_TRACE_RECORDS_SUCCESS = 'FETCH_TRACE_RECORDS_SUCCESS';
export const FETCH_TRACE_RECORDS_FAILED = 'FETCH_TRACE_RECORDS_FAILED';
export const SET_SELECTED_TRACE_RECORD = 'SET_SELECTED_TRACE_RECORD';
export const START_FETCH_TRACE_RECORD = 'START_FETCH_TRACE_RECORD';
export const FETCH_TRACE_RECORD_SUCCESS = 'FETCH_TRACE_RECORD_SUCCESS';
export const FETCH_TRACE_RECORD_FAILED = 'FETCH_TRACE_RECORD_FAILED';
export const PREPEND_LATEST_TRACE_RECORDS = 'PREPEND_LATEST_TRACE_RECORDS';
export const START_FETCH_LATEST_TRACE_RECORDS = 'START_FETCH_LATEST_TRACE_RECORDS';
export const FETCH_LATEST_TRACE_RECORDS_SUCCESS = 'FETCH_LATEST_TRACE_RECORDS_SUCCESS';
export const FETCH_LATEST_TRACE_RECORDS_FAILED = 'FETCH_LATEST_TRACE_RECORDS_FAILED';

// Trace Record Betting
export const START_FETCH_TRACE_RECORD_BETTINGS = 'START_FETCH_TRACE_RECORD_BETTINGS';
export const FETCH_TRACE_RECORD_BETTINGS_SUCCESS = 'FETCH_TRACE_RECORD_BETTINGS_SUCCESS';
export const FETCH_TRACE_RECORD_BETTINGS_FAILED = 'FETCH_TRACE_RECORD_BETTINGS_FAILED';
export const START_DISCARD_TRACE_RECORD_BETTINGS = 'START_DISCARD_TRACE_RECORD_BETTINGS';
export const DISCARD_TRACE_RECORD_BETTINGS_SUCCESS = 'DISCARD_TRACE_RECORD_BETTINGS_SUCCESS';
export const DISCARD_TRACE_RECORD_BETTINGS_FAILED = 'DISCARD_TRACE_RECORD_BETTINGS_FAILED';

// Drawing
export const START_FETCH_LOTTERY_DRAWINGS = 'START_FETCH_LOTTERY_DRAWINGS';
export const FETCH_LOTTERY_DRAWINGS_SUCCESS = 'FETCH_LOTTERY_DRAWINGS_SUCCESS';
export const FETCH_LOTTERY_DRAWINGS_FAILED = 'FETCH_LOTTERY_DRAWINGS_FAILED';
export const START_UPDATE_LOTTERY_DRAWINGS_INTERVAL = 'START_UPDATE_LOTTERY_DRAWINGS_INTERVAL';
export const STOP_UPDATE_LOTTERY_DRAWINGS_INTERVAL = 'STOP_UPDATE_LOTTERY_DRAWINGS_INTERVAL';
export const START_UPDATE_LOTTERY_DRAWINGS = 'START_UPDATE_LOTTERY_DRAWINGS';

// Play condition
export const START_FETCH_PLAY_CONDITIONS = 'START_FETCH_PLAY_CONDITIONS';
export const FETCH_PLAY_CONDITIONS_SUCCESS = 'FETCH_PLAY_CONDITIONS_SUCCESS';
export const FETCH_PLAY_CONDITIONS_FAILED = 'FETCH_PLAY_CONDITIONS_FAILED';

// Play
export const SET_PLAY_ID = 'SET_PLAY_ID';
export const RESET_PLAY_ID = 'RESET_PLAY_ID';
export const START_FETCH_PLAYS = 'START_FETCH_PLAYS';
export const FETCH_PLAYS_SUCCESS = 'FETCH_PLAYS_SUCCESS';
export const FETCH_PLAYS_FAILED = 'FETCH_PLAYS_FAILED';

// Platform
export const START_FETCH_PLATFORM = 'START_FETCH_PLATFORM';
export const FETCH_PLATFORM_SUCCESS = 'FETCH_PLATFORM_SUCCESS';
export const FETCH_PLATFORM_FAILED = 'FETCH_PLATFORM_FAILED';

// Selected Lottery
export const SET_SELECTED_LOTTERY = 'SET_SELECTED_LOTTERY';
export const CLEAR_SELECTED_LOTTERY = 'CLEAR_SELECTED_LOTTERY';

//qick-select-amount
export const SET_XIN_YONG_QUICK_SELECT_AMOUNT_PER_BET = 'SET_XIN_YONG_QUICK_SELECT_AMOUNT_PER_BET';

//lotteryDrawingRecords
export const START_FETCH_LOTTERY_DRAWING_RECORDS = 'START_FETCH_LOTTERY_DRAWING_RECORDS';
export const FETCH_LOTTERY_DRAWING_RECORDS_SUCCESS = 'FETCH_LOTTERY_DRAWING_RECORDS_SUCCESS';
export const FETCH_LOTTERY_DRAWING_RECORDS_FAILED = 'FETCH_LOTTERY_DRAWING_RECORDS_FAILED';
export const PREPEND_LOTTERY_DRAWING_RECORD = 'PREPEND_LOTTERY_DRAWING_RECORD';
export const CLEAR_LOTTERY_DRAWING_RECORDS = 'CLEAR_LOTTERY_DRAWING_RECORDS';

//Wallets
export const START_FETCH_WALLETS = 'START_FETCH_WALLETS';
export const FETCH_WALLETS_SUCCESS = 'FETCH_WALLETS_SUCCESS';
export const FETCH_WALLETS_FAILED = 'FETCH_WALLETS_FAILED';
export const UPDATE_WALLET = 'UPDATE_WALLET';

//transaction-log
export const START_FETCH_TRANSACTION_LOGS = 'START_FETCH_TRANSACTION_LOGS';
export const FETCH_TRANSACTION_LOGS_SUCCESS = 'FETCH_TRANSACTION_LOGS_SUCCESS';
export const FETCH_TRANSACTION_LOGS_FAILED = 'FETCH_TRANSACTION_LOGS_FAILED';

// transaction-log：dividend
export const START_FETCH_DIVIDEND_TRANSACTION_LOGS = 'START_FETCH_DIVIDEND_TRANSACTION_LOGS';
export const FETCH_DIVIDEND_TRANSACTION_LOGS_SUCCESS = 'FETCH_DIVIDEND_TRANSACTION_LOGS_SUCCESS';
export const FETCH_DIVIDEND_TRANSACTION_LOGS_FAILED = 'FETCH_DIVIDEND_TRANSACTION_LOGS_FAILED';

//Announcements
export const START_FETCH_ANNOUNCEMENTS = 'START_FETCH_ANNOUNCEMENTS';
export const FETCH_ANNOUNCEMENTS_SUCCESS = 'FETCH_ANNOUNCEMENTS_SUCCESS';
export const FETCH_ANNOUNCEMENTS_FAILED = 'FETCH_ANNOUNCEMENTS_FAILED';
export const SET_SELECTED_ANNOUNCEMENT_ID = 'SET_SELECTED_ANNOUNCEMENT_ID';
export const RESET_SELECTED_ANNOUNCEMENT_ID = 'RESET_SELECTED_ANNOUNCEMENT_ID';

//demo Error handling TODO remove after demo
export const START_FETCH_DEMO_ERROR_HANDLING = 'START_FETCH_DEMO_ERROR_HANDLING';
export const FETCH_DEMO_ERROR_HANDLING_SUCCESS = 'FETCH_DEMO_ERROR_HANDLING_SUCCESS';
export const FETCH_DEMO_ERROR_HANDLING_FAILED = 'FETCH_DEMO_ERROR_HANDLING_FAILED';

//security-setting
export const START_FETCH_USER_SECURITY = 'START_FETCH_USER_SECURITY';
export const FETCH_USER_SECURITY_SUCCESS = 'FETCH_USER_SECURITY_SUCCESS';
export const FETCH_USER_SECURITY_FAILED = 'FETCH_USER_SECURITY_FAILED';
export const START_UPDATE_USER_LOGIN_PASSWORD = 'START_UPDATE_USER_LOGIN_PASSWORD';
export const UPDATE_USER_LOGIN_PASSWORD_SUCCESS = 'UPDATE_USER_LOGIN_PASSWORD_SUCCESS';
export const UPDATE_USER_LOGIN_PASSWORD_FAILED = 'UPDATE_USER_LOGIN_PASSWORD_FAILED';
export const START_UPDATE_USER_BET_PASSWORD = 'START_UPDATE_USER_BET_PASSWORD';
export const UPDATE_USER_BET_PASSWORD_SUCCESS = 'UPDATE_USER_BET_PASSWORD_SUCCESS';
export const UPDATE_USER_BET_PASSWORD_FAILED = 'UPDATE_USER_BET_PASSWORD_FAILED';
export const START_UPDATE_USER_FUNDS_PASSWORD = 'START_UPDATE_USER_FUNDS_PASSWORD';
export const UPDATE_USER_FUNDS_PASSWORD_SUCCESS = 'UPDATE_USER_FUNDS_PASSWORD_SUCCESS';
export const UPDATE_USER_FUNDS_PASSWORD_FAILED = 'UPDATE_USER_FUNDS_PASSWORD_FAILED';
export const START_ENABLE_LOGIN_GEO_VALIDATION = 'START_ENABLE_LOGIN_GEO_VALIDATION';
export const ENABLE_LOGIN_GEO_VALIDATION_SUCCESS = 'ENABLE_LOGIN_GEO_VALIDATION_SUCCESS';
export const ENABLE_LOGIN_GEO_VALIDATION_FAILED = 'ENABLE_LOGIN_GEO_VALIDATION_FAILED';
export const START_DISABLE_LOGIN_GEO_VALIDATION = 'START_DISABLE_LOGIN_GEO_VALIDATION';
export const DISABLE_LOGIN_GEO_VALIDATION_SUCCESS = 'DISABLE_LOGIN_GEO_VALIDATION_SUCCESS';
export const DISABLE_LOGIN_GEO_VALIDATION_FAILED = 'DISABLE_LOGIN_GEO_VALIDATION_FAILED';
export const START_UPDATE_USER_SECURITY_QUESTIONS = 'START_UPDATE_USER_SECURITY_QUESTIONS';
export const UPDATE_USER_SECURITY_QUESTIONS_SUCCESS = 'UPDATE_USER_SECURITY_QUESTIONS_SUCCESS';
export const UPDATE_USER_SECURITY_QUESTIONS_FAILED = 'UPDATE_USER_SECURITY_QUESTIONS_FAILED';
export const START_BIND_GOOGLE_AUTHENTICATION = 'START_BIND_GOOGLE_AUTHENTICATION';
export const BIND_GOOGLE_AUTHENTICATION_SUCCESS = 'BIND_GOOGLE_AUTHENTICATION_SUCCESS';
export const BIND_GOOGLE_AUTHENTICATION_FAILED = 'BIND_GOOGLE_AUTHENTICATION_FAILED';
export const START_UNBIND_GOOGLE_AUTHENTICATION = 'START_UNBIND_GOOGLE_AUTHENTICATION';
export const UNBIND_GOOGLE_AUTHENTICATION_SUCCESS = 'UNBIND_GOOGLE_AUTHENTICATION_SUCCESS';
export const UNBIND_GOOGLE_AUTHENTICATION_FAILED = 'UNBIND_GOOGLE_AUTHENTICATION_FAILED';
export const START_UPDATE_USER_LOGIN_PASSWORD_VIA_SECURITY_QUESTIONS = 'START_UPDATE_USER_LOGIN_PASSWORD_VIA_SECURITY_QUESTIONS';
export const UPDATE_USER_LOGIN_PASSWORD_VIA_SECURITY_QUESTIONS_SUCCESS = 'UPDATE_USER_LOGIN_PASSWORD_VIA_SECURITY_QUESTIONS_SUCCESS';
export const UPDATE_USER_LOGIN_PASSWORD_VIA_SECURITY_QUESTIONS_FAILED = 'UPDATE_USER_LOGIN_PASSWORD_VIA_SECURITY_QUESTIONS_FAILED';
export const START_UPDATE_USER_BET_PASSWORD_VIA_SECURITY_QUESTIONS = 'START_UPDATE_USER_BET_PASSWORD_VIA_SECURITY_QUESTIONS';
export const UPDATE_USER_BET_PASSWORD_VIA_SECURITY_QUESTIONS_SUCCESS = 'UPDATE_USER_BET_PASSWORD_VIA_SECURITY_QUESTIONS_SUCCESS';
export const UPDATE_USER_BET_PASSWORD_VIA_SECURITY_QUESTIONS_FAILED = 'UPDATE_USER_BET_PASSWORD_VIA_SECURITY_QUESTIONS_FAILED';
export const START_UPDATE_USER_FUNDS_PASSWORD_VIA_SECURITY_QUESTIONS = 'START_UPDATE_USER_FUNDS_PASSWORD_VIA_SECURITY_QUESTIONS';
export const UPDATE_USER_FUNDS_PASSWORD_VIA_SECURITY_QUESTIONS_SUCCESS = 'UPDATE_USER_FUNDS_PASSWORD_VIA_SECURITY_QUESTIONS_SUCCESS';
export const UPDATE_USER_FUNDS_PASSWORD_VIA_SECURITY_QUESTIONS_FAILED = 'UPDATE_USER_FUNDS_PASSWORD_VIA_SECURITY_QUESTIONS_FAILED';
export const START_UPDATE_USER_LOGIN_PASSWORD_VIA_GOOGLE_TOTP = 'START_UPDATE_USER_LOGIN_PASSWORD_VIA_GOOGLE_TOTP';
export const UPDATE_USER_LOGIN_PASSWORD_VIA_GOOGLE_TOTP_SUCCESS = 'UPDATE_USER_LOGIN_PASSWORD_VIA_GOOGLE_TOTP_SUCCESS';
export const UPDATE_USER_LOGIN_PASSWORD_VIA_GOOGLE_TOTP_FAILED = 'UPDATE_USER_LOGIN_PASSWORD_VIA_GOOGLE_TOTP_FAILED';
export const START_UPDATE_USER_BET_PASSWORD_VIA_GOOGLE_TOTP = 'START_UPDATE_USER_BET_PASSWORD_VIA_GOOGLE_TOTP';
export const UPDATE_USER_BET_PASSWORD_VIA_GOOGLE_TOTP_SUCCESS = 'UPDATE_USER_BET_PASSWORD_VIA_GOOGLE_TOTP_SUCCESS';
export const UPDATE_USER_BET_PASSWORD_VIA_GOOGLE_TOTP_FAILED = 'UPDATE_USER_BET_PASSWORD_VIA_GOOGLE_TOTP_FAILED';
export const START_UPDATE_USER_FUNDS_PASSWORD_VIA_GOOGLE_TOTP = 'START_UPDATE_USER_FUNDS_PASSWORD_VIA_GOOGLE_TOTP';
export const UPDATE_USER_FUNDS_PASSWORD_VIA_GOOGLE_TOTP_SUCCESS = 'UPDATE_USER_FUNDS_PASSWORD_VIA_GOOGLE_TOTP_SUCCESS';
export const UPDATE_USER_FUNDS_PASSWORD_VIA_GOOGLE_TOTP_FAILED = 'UPDATE_USER_FUNDS_PASSWORD_VIA_GOOGLE_TOTP_FAILED';

//Security Question
export const START_FETCH_SECURITY_QUESTIONS = 'START_FETCH_SECURITY_QUESTIONS';
export const FETCH_SECURITY_QUESTIONS_SUCCESS = 'FETCH_SECURITY_QUESTIONS_SUCCESS';
export const FETCH_SECURITY_QUESTIONS_FAILED = 'FETCH_SECURITY_QUESTIONS_FAILED';

//bank-cards
export const START_FETCH_USER_BANK_CARDS = 'START_FETCH_USER_BANK_CARDS';
export const FETCH_USER_BANK_CARDS_SUCCESS = 'FETCH_USER_BANK_CARDS_SUCCESS';
export const FETCH_USER_BANK_CARDS_FAILED = 'FETCH_USER_BANK_CARDS_FAILED';
export const START_CREATE_USER_BANK_CARD = 'START_CREATE_USER_BANK_CARD';
export const CREATE_USER_BANK_CARD_SUCCESS = 'CREATE_USER_BANK_CARD_SUCCESS';
export const CREATE_USER_BANK_CARD_FAILED = 'CREATE_USER_BANK_CARD_FAILED';
export const START_DELETE_USER_BANK_CARD = 'START_DELETE_USER_BANK_CARD';
export const DELETE_USER_BANK_CARD_SUCCESS = 'DELETE_USER_BANK_CARD_SUCCESS';
export const DELETE_USER_BANK_CARD_FAILED = 'DELETE_USER_BANK_CARD_FAILED';

//stats
export const START_FETCH_USER_STATS = 'START_FETCH_USER_STATS';
export const FETCH_USER_STATS_SUCCESS = 'FETCH_USER_STATS_SUCCESS';
export const FETCH_USER_STATS_FAILED = 'FETCH_USER_STATS_FAILED';

// Fixed Wage
export const START_FETCH_FIXED_WAGES = 'START_FETCH_FIXED_WAGES';
export const FETCH_FIXED_WAGES_SUCCESS = 'FETCH_FIXED_WAGES_SUCCESS';
export const FETCH_FIXED_WAGES_FAILED = 'FETCH_FIXED_WAGES_FAILED';
export const START_UPDATE_USER_FIXED_WAGE = 'START_UPDATE_USER_FIXED_WAGE';
export const UPDATE_USER_FIXED_WAGE_SUCCESS = 'UPDATE_USER_FIXED_WAGE_SUCCESS';
export const UPDATE_USER_FIXED_WAGE_FAILED = 'UPDATE_USER_FIXED_WAGE_FAILED';

// Dividend Management
export const START_FETCH_DIVIDENDS = 'START_FETCH_DIVIDENDS';
export const FETCH_DIVIDENDS_SUCCESS = 'FETCH_DIVIDENDS_SUCCESS';
export const FETCH_DIVIDENDS_FAILED = 'FETCH_DIVIDENDS_FAILED';

export const START_FETCH_DIVIDEND_DURATIONS = 'START_FETCH_DIVIDEND_DURATIONS';
export const FETCH_DIVIDEND_DURATIONS_SUCCESS = 'FETCH_DIVIDEND_DURATIONS_SUCCESS';
export const FETCH_DIVIDEND_DURATIONS_FAILED = 'FETCH_DIVIDEND_DURATIONS_FAILED';

export const START_FETCH_DIVIDEND_SETTINGS_SELF = 'START_FETCH_DIVIDEND_SETTINGS_SELF';
export const FETCH_DIVIDEND_SETTINGS_SELF_SUCCESS = 'FETCH_DIVIDEND_SETTINGS_SELF_SUCCESS';
export const FETCH_DIVIDEND_SETTINGS_SELF_FAILED = 'FETCH_DIVIDEND_SETTINGS_SELF_FAILED';

export const START_FETCH_DIVIDEND_SETTINGS_TEMPLATE = 'START_FETCH_DIVIDEND_SETTINGS_TEMPLATE';
export const FETCH_DIVIDEND_SETTINGS_TEMPLATE_SUCCESS = 'FETCH_DIVIDEND_SETTINGS_TEMPLATE_SUCCESS';
export const FETCH_DIVIDEND_SETTINGS_TEMPLATE_FAILED = 'FETCH_DIVIDEND_SETTINGS_TEMPLATE_FAILED';

export const START_UPDATE_DIVIDEND_SETTINGS_TEMPLATE = 'START_UPDATE_DIVIDEND_SETTINGS_TEMPLATE';
export const UPDATE_DIVIDEND_SETTINGS_TEMPLATE_SUCCESS = 'UPDATE_DIVIDEND_SETTINGS_TEMPLATE_SUCCESS';
export const UPDATE_DIVIDEND_SETTINGS_TEMPLATE_FAILED = 'UPDATE_DIVIDEND_SETTINGS_TEMPLATE_FAILED';

export const START_UPDATE_CHILDREN_DIVIDEND_SETTINGS = 'START_UPDATE_CHILDREN_DIVIDEND_SETTINGS';
export const UPDATE_CHILDREN_DIVIDEND_SETTINGS_SUCCESS = 'UPDATE_CHILDREN_DIVIDEND_SETTINGS_SUCCESS';
export const UPDATE_CHILDREN_DIVIDEND_SETTINGS_FAILED = 'UPDATE_CHILDREN_DIVIDEND_SETTINGS_FAILED';

export const START_GRANT_DIVIDENDS = 'START_GRANT_DIVIDENDS';
export const GRANT_DIVIDENDS_SUCCESS = 'GRANT_DIVIDENDS_SUCCESS';
export const GRANT_DIVIDENDS_FAILED = 'GRANT_DIVIDENDS_FAILED';

// Team Report
export const START_FETCH_TEAM_REPORTS = 'START_FETCH_TEAM_REPORTS';
export const FETCH_TEAM_REPORTS_SUCCESS = 'FETCH_TEAM_REPORTS_SUCCESS';
export const FETCH_TEAM_REPORTS_FAILED = 'FETCH_TEAM_REPORTS_FAILED';

// Team Stats
export const START_FETCH_TEAM_STATS = 'START_FETCH_TEAM_STATS';
export const FETCH_TEAM_STATS_SUCCESS = 'FETCH_TEAM_STATS_SUCCESS';
export const FETCH_TEAM_STATS_FAILED = 'FETCH_TEAM_STATS_FAILED';
